# Automatically generated by configure - do not modify
SRC_PATH=/home/gaodi/qemu/roms/vgabios
AS=x86_64-w64-mingw32-as
CCAS=x86_64-w64-mingw32-gcc
CC=x86_64-w64-mingw32-gcc
BCC=bcc
CPP=x86_64-w64-mingw32-gcc -E
OBJCOPY=objcopy
IASL=iasl
LD=x86_64-w64-mingw32-ld
RANLIB=x86_64-w64-mingw32-ranlib
