
#ifndef ALL_GL_H
#define ALL_GL_H

#include <GLES/glplatform.h>
#include <GLES/gl.h>
#include <GLES2/gl2.h>
#include <GLES2/gl2platform.h>
#include <GLES2/gl2ext.h>
#include <GLES3/gl3.h>
GLenum d_glCheckFramebufferStatus(void *context, GLenum target);
GLuint d_glCreateShaderProgramv(void *context, GLenum type, GLsizei count, const GLchar*const* strings);
GLbitfield d_glQueryMatrixxOES(void *context, GLfixed* mantissa, GLint* exponent);
void d_glGetFramebufferAttachmentParameteriv(void *context, GLenum target, GLenum attachment, GLenum pname, GLint* params);
void d_glGetProgramInfoLog(void *context, GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
void d_glGetRenderbufferParameteriv(void *context, GLenum target, GLenum pname, GLint* params);
void d_glGetShaderInfoLog(void *context, GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
void d_glGetShaderPrecisionFormat(void *context, GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
void d_glGetShaderSource(void *context, GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* source);
void d_glGetTexParameterfv(void *context, GLenum target, GLenum pname, GLfloat* params);
void d_glGetTexParameteriv(void *context, GLenum target, GLenum pname, GLint* params);
void d_glGetQueryiv(void *context, GLenum target, GLenum pname, GLint* params);
void d_glGetQueryObjectuiv(void *context, GLuint id, GLenum pname, GLuint* params);
void d_glGetTransformFeedbackVarying(void *context, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLsizei* size, GLenum* type, GLchar* name);
void d_glGetActiveUniformsiv(void *context, GLuint program, GLsizei uniformCount, const GLuint* uniformIndices, GLenum pname, GLint* params);
void d_glGetActiveUniformBlockiv(void *context, GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint* params);
void d_glGetActiveUniformBlockName(void *context, GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei* length, GLchar* uniformBlockName);
void d_glGetSamplerParameteriv(void *context, GLuint sampler, GLenum pname, GLint* params);
void d_glGetSamplerParameterfv(void *context, GLuint sampler, GLenum pname, GLfloat* params);
void d_glGetProgramBinary(void *context, GLuint program, GLsizei bufSize, GLsizei* length, GLenum* binaryFormat, void* binary);
void d_glGetInternalformativ(void *context, GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint* params);
void d_glGetClipPlanexOES(void *context, GLenum plane, GLfixed* equation);
void d_glGetFixedvOES(void *context, GLenum pname, GLfixed* params);
void d_glGetTexEnvxvOES(void *context, GLenum target, GLenum pname, GLfixed* params);
void d_glGetTexParameterxvOES(void *context, GLenum target, GLenum pname, GLfixed* params);
void d_glGetLightxvOES(void *context, GLenum light, GLenum pname, GLfixed* params);
void d_glGetMaterialxvOES(void *context, GLenum face, GLenum pname, GLfixed* params);
void d_glGetTexGenxvOES(void *context, GLenum coord, GLenum pname, GLfixed* params);
void d_glReadPixels_with_bound(void *context, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLintptr pixels);
void d_glGetFramebufferParameteriv(void *context, GLenum target, GLenum pname, GLint* params);
void d_glGetProgramInterfaceiv(void *context, GLuint program, GLenum programInterface, GLenum pname, GLint* params);
void d_glGetProgramResourceName(void *context, GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei* length, GLchar* name);
void d_glGetProgramResourceiv(void *context, GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum* props, GLsizei bufSize, GLsizei* length, GLint* params);
void d_glGetProgramPipelineiv(void *context, GLuint pipeline, GLenum pname, GLint* params);
void d_glGetProgramPipelineInfoLog(void *context, GLuint pipeline, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
void d_glGetMultisamplefv(void *context, GLenum pname, GLuint index, GLfloat* val);
void d_glGetTexLevelParameteriv(void *context, GLenum target, GLint level, GLenum pname, GLint* params);
void d_glGetTexLevelParameterfv(void *context, GLenum target, GLint level, GLenum pname, GLfloat* params);
GLsync d_glFenceSync(void *context, GLenum condition, GLbitfield flags);
GLboolean d_glIsSync(void *context, GLsync sync);
void d_glGetSynciv(void *context, GLsync sync, GLenum pname, GLsizei bufSize, GLsizei* length, GLint* values);
GLenum d_glClientWaitSync(void *context, GLsync sync, GLbitfield flags, GLuint64 timeout);
void d_glFinish(void *context);
GLint d_glTestInt1(void *context, GLint a, GLuint b);
GLuint d_glTestInt2(void *context, GLint a, GLuint b);
GLint64 d_glTestInt3(void *context, GLint64 a, GLuint64 b);
GLuint64 d_glTestInt4(void *context, GLint64 a, GLuint64 b);
GLfloat d_glTestInt5(void *context, GLint a, GLuint b);
GLdouble d_glTestInt6(void *context, GLint a, GLuint b);
void d_glTestPointer1(void *context, GLint a, const GLint* b);
void d_glTestPointer2(void *context, GLint a, const GLint* b, GLint* c);
GLint d_glTestPointer4(void *context, GLint a, const GLint* b, GLint* c);
void d_glTestString(void *context, GLint a, GLint count, const GLchar*const* strings, GLint buf_len, GLchar* char_buf);
void d_glMapBufferRange_read(void *context, GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access, void* mem_buf);
void d_glReadPixels_without_bound(void *context, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
GLint d_glTestPointer3(void *context, GLint a, const GLint* b, GLint* c);
GLenum d_glGetError_origin(void *context);
GLenum d_glGetError(void *context);
GLboolean d_glIsBuffer_origin(void *context, GLuint buffer);
GLboolean d_glIsBuffer(void *context, GLuint buffer);
GLboolean d_glIsEnabled_origin(void *context, GLenum cap);
GLboolean d_glIsEnabled(void *context, GLenum cap);
GLboolean d_glIsFramebuffer_origin(void *context, GLuint framebuffer);
GLboolean d_glIsFramebuffer(void *context, GLuint framebuffer);
GLboolean d_glIsProgram_origin(void *context, GLuint program);
GLboolean d_glIsProgram(void *context, GLuint program);
GLboolean d_glIsRenderbuffer_origin(void *context, GLuint renderbuffer);
GLboolean d_glIsRenderbuffer(void *context, GLuint renderbuffer);
GLboolean d_glIsShader_origin(void *context, GLuint shader);
GLboolean d_glIsShader(void *context, GLuint shader);
GLboolean d_glIsTexture_origin(void *context, GLuint texture);
GLboolean d_glIsTexture(void *context, GLuint texture);
GLboolean d_glIsQuery_origin(void *context, GLuint id);
GLboolean d_glIsQuery(void *context, GLuint id);
GLboolean d_glIsVertexArray_origin(void *context, GLuint array);
GLboolean d_glIsVertexArray(void *context, GLuint array);
GLboolean d_glIsSampler_origin(void *context, GLuint sampler);
GLboolean d_glIsSampler(void *context, GLuint sampler);
GLboolean d_glIsTransformFeedback_origin(void *context, GLuint id);
GLboolean d_glIsTransformFeedback(void *context, GLuint id);
GLint d_glGetAttribLocation_origin(void *context, GLuint program, const GLchar* name);
GLint d_glGetAttribLocation(void *context, GLuint program, const GLchar* name);
GLint d_glGetUniformLocation_origin(void *context, GLuint program, const GLchar* name);
GLint d_glGetUniformLocation(void *context, GLuint program, const GLchar* name);
GLint d_glGetFragDataLocation_origin(void *context, GLuint program, const GLchar* name);
GLint d_glGetFragDataLocation(void *context, GLuint program, const GLchar* name);
GLuint d_glGetUniformBlockIndex_origin(void *context, GLuint program, const GLchar* uniformBlockName);
GLuint d_glGetUniformBlockIndex(void *context, GLuint program, const GLchar* uniformBlockName);
GLuint d_glGetProgramResourceIndex_origin(void *context, GLuint program, GLenum programInterface, const GLchar* name);
GLuint d_glGetProgramResourceIndex(void *context, GLuint program, GLenum programInterface, const GLchar* name);
GLint d_glGetProgramResourceLocation_origin(void *context, GLuint program, GLenum programInterface, const GLchar* name);
GLint d_glGetProgramResourceLocation(void *context, GLuint program, GLenum programInterface, const GLchar* name);
void d_glGetActiveAttrib_origin(void *context, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
void d_glGetActiveAttrib(void *context, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
void d_glGetActiveUniform_origin(void *context, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
void d_glGetActiveUniform(void *context, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
void d_glGetAttachedShaders_origin(void *context, GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders);
void d_glGetAttachedShaders(void *context, GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders);
void d_glGetProgramiv_origin(void *context, GLuint program, GLenum pname, GLint* params);
void d_glGetProgramiv(void *context, GLuint program, GLenum pname, GLint* params);
void d_glGetShaderiv_origin(void *context, GLuint shader, GLenum pname, GLint* params);
void d_glGetShaderiv(void *context, GLuint shader, GLenum pname, GLint* params);
void d_glGetUniformfv_origin(void *context, GLuint program, GLint location, GLfloat* params);
void d_glGetUniformfv(void *context, GLuint program, GLint location, GLfloat* params);
void d_glGetUniformiv_origin(void *context, GLuint program, GLint location, GLint* params);
void d_glGetUniformiv(void *context, GLuint program, GLint location, GLint* params);
void d_glGetUniformuiv_origin(void *context, GLuint program, GLint location, GLuint* params);
void d_glGetUniformuiv(void *context, GLuint program, GLint location, GLuint* params);
void d_glGetUniformIndices_origin(void *context, GLuint program, GLsizei uniformCount, const GLchar*const* uniformNames, GLuint* uniformIndices);
void d_glGetUniformIndices(void *context, GLuint program, GLsizei uniformCount, const GLchar*const* uniformNames, GLuint* uniformIndices);
void d_glGetVertexAttribfv_origin(void *context, GLuint index, GLenum pname, GLfloat* params);
void d_glGetVertexAttribiv_origin(void *context, GLuint index, GLenum pname, GLint* params);
void d_glGetVertexAttribIiv_origin(void *context, GLuint index, GLenum pname, GLint* params);
void d_glGetVertexAttribIuiv_origin(void *context, GLuint index, GLenum pname, GLuint* params);
void d_glGetBufferParameteriv_origin(void *context, GLenum target, GLenum pname, GLint* params);
void d_glGetBufferParameteriv(void *context, GLenum target, GLenum pname, GLint* params);
void d_glGetBufferParameteri64v_origin(void *context, GLenum target, GLenum pname, GLint64* params);
void d_glGetBufferParameteri64v(void *context, GLenum target, GLenum pname, GLint64* params);
void d_glGetBooleanv_origin(void *context, GLenum pname, GLboolean* data);
void d_glGetBooleanv(void *context, GLenum pname, GLboolean* data);
void d_glGetBooleani_v_origin(void *context, GLenum target, GLuint index, GLboolean* data);
void d_glGetBooleani_v(void *context, GLenum target, GLuint index, GLboolean* data);
void d_glGetFloatv_origin(void *context, GLenum pname, GLfloat* data);
void d_glGetFloatv(void *context, GLenum pname, GLfloat* data);
void d_glGetIntegerv_origin(void *context, GLenum pname, GLint* data);
void d_glGetIntegerv(void *context, GLenum pname, GLint* data);
void d_glGetIntegeri_v_origin(void *context, GLenum target, GLuint index, GLint* data);
void d_glGetIntegeri_v(void *context, GLenum target, GLuint index, GLint* data);
void d_glGetInteger64v_origin(void *context, GLenum pname, GLint64* data);
void d_glGetInteger64v(void *context, GLenum pname, GLint64* data);
void d_glGetInteger64i_v_origin(void *context, GLenum target, GLuint index, GLint64* data);
void d_glGetInteger64i_v(void *context, GLenum target, GLuint index, GLint64* data);
void d_glActiveTexture(void *context, GLenum texture);
void d_glAttachShader(void *context, GLuint program, GLuint shader);
void d_glBindBuffer_origin(void *context, GLenum target, GLuint buffer);
void d_glBindFramebuffer(void *context, GLenum target, GLuint framebuffer);
void d_glBindRenderbuffer(void *context, GLenum target, GLuint renderbuffer);
void d_glBindTexture(void *context, GLenum target, GLuint texture);
void d_glBlendColor(void *context, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void d_glBlendEquation(void *context, GLenum mode);
void d_glBlendEquationSeparate(void *context, GLenum modeRGB, GLenum modeAlpha);
void d_glBlendFunc(void *context, GLenum sfactor, GLenum dfactor);
void d_glBlendFuncSeparate(void *context, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void d_glClear(void *context, GLbitfield mask);
void d_glClearColor(void *context, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void d_glClearDepthf(void *context, GLfloat d);
void d_glClearStencil(void *context, GLint s);
void d_glColorMask(void *context, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void d_glCompileShader(void *context, GLuint shader);
void d_glCopyTexImage2D(void *context, GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void d_glCopyTexSubImage2D(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void d_glCullFace(void *context, GLenum mode);
void d_glDeleteProgram_origin(void *context, GLuint program);
void d_glDeleteShader(void *context, GLuint shader);
void d_glDepthFunc(void *context, GLenum func);
void d_glDepthMask(void *context, GLboolean flag);
void d_glDepthRangef(void *context, GLfloat n, GLfloat f);
void d_glDetachShader(void *context, GLuint program, GLuint shader);
void d_glDisable(void *context, GLenum cap);
void d_glDisableVertexAttribArray_origin(void *context, GLuint index);
void d_glDrawArrays_origin(void *context, GLenum mode, GLint first, GLsizei count);
void d_glEnable(void *context, GLenum cap);
void d_glEnableVertexAttribArray_origin(void *context, GLuint index);
void d_glFlush(void *context);
void d_glFramebufferRenderbuffer(void *context, GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void d_glFramebufferTexture2D(void *context, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void d_glFrontFace(void *context, GLenum mode);
void d_glGenerateMipmap(void *context, GLenum target);
void d_glHint(void *context, GLenum target, GLenum mode);
void d_glLineWidth(void *context, GLfloat width);
void d_glLinkProgram_origin(void *context, GLuint program);
void d_glPixelStorei_origin(void *context, GLenum pname, GLint param);
void d_glPolygonOffset(void *context, GLfloat factor, GLfloat units);
void d_glReleaseShaderCompiler(void *context);
void d_glRenderbufferStorage(void *context, GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void d_glSampleCoverage(void *context, GLfloat value, GLboolean invert);
void d_glScissor(void *context, GLint x, GLint y, GLsizei width, GLsizei height);
void d_glStencilFunc(void *context, GLenum func, GLint ref, GLuint mask);
void d_glStencilFuncSeparate(void *context, GLenum face, GLenum func, GLint ref, GLuint mask);
void d_glStencilMask(void *context, GLuint mask);
void d_glStencilMaskSeparate(void *context, GLenum face, GLuint mask);
void d_glStencilOp(void *context, GLenum fail, GLenum zfail, GLenum zpass);
void d_glStencilOpSeparate(void *context, GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void d_glTexParameterf(void *context, GLenum target, GLenum pname, GLfloat param);
void d_glTexParameteri(void *context, GLenum target, GLenum pname, GLint param);
void d_glUniform1f(void *context, GLint location, GLfloat v0);
void d_glUniform1i(void *context, GLint location, GLint v0);
void d_glUniform2f(void *context, GLint location, GLfloat v0, GLfloat v1);
void d_glUniform2i(void *context, GLint location, GLint v0, GLint v1);
void d_glUniform3f(void *context, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void d_glUniform3i(void *context, GLint location, GLint v0, GLint v1, GLint v2);
void d_glUniform4f(void *context, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void d_glUniform4i(void *context, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void d_glUseProgram(void *context, GLuint program);
void d_glValidateProgram(void *context, GLuint program);
void d_glVertexAttrib1f(void *context, GLuint index, GLfloat x);
void d_glVertexAttrib2f(void *context, GLuint index, GLfloat x, GLfloat y);
void d_glVertexAttrib3f(void *context, GLuint index, GLfloat x, GLfloat y, GLfloat z);
void d_glVertexAttrib4f(void *context, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void d_glViewport(void *context, GLint x, GLint y, GLsizei width, GLsizei height);
void d_glReadBuffer(void *context, GLenum src);
void d_glCopyTexSubImage3D(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void d_glBeginQuery(void *context, GLenum target, GLuint id);
void d_glEndQuery(void *context, GLenum target);
void d_glBlitFramebuffer(void *context, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
void d_glRenderbufferStorageMultisample(void *context, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void d_glFramebufferTextureLayer(void *context, GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
void d_glBindVertexArray_origin(void *context, GLuint array);
void d_glBeginTransformFeedback(void *context, GLenum primitiveMode);
void d_glEndTransformFeedback(void *context);
void d_glBindBufferRange(void *context, GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void d_glBindBufferBase(void *context, GLenum target, GLuint index, GLuint buffer);
void d_glVertexAttribI4i(void *context, GLuint index, GLint x, GLint y, GLint z, GLint w);
void d_glVertexAttribI4ui(void *context, GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
void d_glUniform1ui(void *context, GLint location, GLuint v0);
void d_glUniform2ui(void *context, GLint location, GLuint v0, GLuint v1);
void d_glUniform3ui(void *context, GLint location, GLuint v0, GLuint v1, GLuint v2);
void d_glUniform4ui(void *context, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void d_glClearBufferfi(void *context, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
void d_glCopyBufferSubData(void *context, GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void d_glUniformBlockBinding(void *context, GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
void d_glDrawArraysInstanced_origin(void *context, GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
void d_glBindSampler(void *context, GLuint unit, GLuint sampler);
void d_glSamplerParameteri(void *context, GLuint sampler, GLenum pname, GLint param);
void d_glSamplerParameterf(void *context, GLuint sampler, GLenum pname, GLfloat param);
void d_glVertexAttribDivisor_origin(void *context, GLuint index, GLuint divisor);
void d_glBindTransformFeedback(void *context, GLenum target, GLuint id);
void d_glPauseTransformFeedback(void *context);
void d_glResumeTransformFeedback(void *context);
void d_glProgramParameteri(void *context, GLuint program, GLenum pname, GLint value);
void d_glTexStorage2D(void *context, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void d_glTexStorage3D(void *context, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
void d_glAlphaFuncxOES(void *context, GLenum func, GLfixed ref);
void d_glClearColorxOES(void *context, GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
void d_glClearDepthxOES(void *context, GLfixed depth);
void d_glColor4xOES(void *context, GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
void d_glDepthRangexOES(void *context, GLfixed n, GLfixed f);
void d_glFogxOES(void *context, GLenum pname, GLfixed param);
void d_glFrustumxOES(void *context, GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f);
void d_glLightModelxOES(void *context, GLenum pname, GLfixed param);
void d_glLightxOES(void *context, GLenum light, GLenum pname, GLfixed param);
void d_glLineWidthxOES(void *context, GLfixed width);
void d_glMaterialxOES(void *context, GLenum face, GLenum pname, GLfixed param);
void d_glMultiTexCoord4xOES(void *context, GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q);
void d_glNormal3xOES(void *context, GLfixed nx, GLfixed ny, GLfixed nz);
void d_glOrthoxOES(void *context, GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f);
void d_glPointSizexOES(void *context, GLfixed size);
void d_glPolygonOffsetxOES(void *context, GLfixed factor, GLfixed units);
void d_glRotatexOES(void *context, GLfixed angle, GLfixed x, GLfixed y, GLfixed z);
void d_glScalexOES(void *context, GLfixed x, GLfixed y, GLfixed z);
void d_glTexEnvxOES(void *context, GLenum target, GLenum pname, GLfixed param);
void d_glTranslatexOES(void *context, GLfixed x, GLfixed y, GLfixed z);
void d_glPointParameterxOES(void *context, GLenum pname, GLfixed param);
void d_glSampleCoveragexOES(void *context, GLclampx value, GLboolean invert);
void d_glTexGenxOES(void *context, GLenum coord, GLenum pname, GLfixed param);
void d_glClearDepthfOES(void *context, GLclampf depth);
void d_glDepthRangefOES(void *context, GLclampf n, GLclampf f);
void d_glFrustumfOES(void *context, GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f);
void d_glOrthofOES(void *context, GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f);
void d_glRenderbufferStorageMultisampleEXT(void *context, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void d_glUseProgramStages(void *context, GLuint pipeline, GLbitfield stages, GLuint program);
void d_glActiveShaderProgram(void *context, GLuint pipeline, GLuint program);
void d_glProgramUniform1i(void *context, GLuint program, GLint location, GLint v0);
void d_glProgramUniform2i(void *context, GLuint program, GLint location, GLint v0, GLint v1);
void d_glProgramUniform3i(void *context, GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
void d_glProgramUniform4i(void *context, GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void d_glProgramUniform1ui(void *context, GLuint program, GLint location, GLuint v0);
void d_glProgramUniform2ui(void *context, GLuint program, GLint location, GLuint v0, GLuint v1);
void d_glProgramUniform3ui(void *context, GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
void d_glProgramUniform4ui(void *context, GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void d_glProgramUniform1f(void *context, GLuint program, GLint location, GLfloat v0);
void d_glProgramUniform2f(void *context, GLuint program, GLint location, GLfloat v0, GLfloat v1);
void d_glProgramUniform3f(void *context, GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void d_glProgramUniform4f(void *context, GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void d_glShaderSource_origin(void *context, GLuint shader, GLsizei count, const GLint* length, const GLchar*const* string);
void d_glTransformFeedbackVaryings(void *context, GLuint program, GLsizei count, const GLchar*const* varyings, GLenum bufferMode);
void d_glDeleteBuffers_origin(void *context, GLsizei n, const GLuint* buffers);
void d_glDeleteFramebuffers(void *context, GLsizei n, const GLuint* framebuffers);
void d_glDeleteRenderbuffers(void *context, GLsizei n, const GLuint* renderbuffers);
void d_glDeleteTextures(void *context, GLsizei n, const GLuint* textures);
void d_glDrawElements_with_bound(void *context, GLenum mode, GLsizei count, GLenum type, GLsizeiptr indices);
void d_glShaderBinary(void *context, GLsizei count, const GLuint* shaders, GLenum binaryFormat, const void* binary, GLsizei length);
void d_glCompressedTexSubImage2D_with_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, GLintptr data);
void d_glTexImage2D_with_bound(void *context, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, GLintptr pixels);
void d_glTexParameterfv(void *context, GLenum target, GLenum pname, const GLfloat* params);
void d_glTexParameteriv(void *context, GLenum target, GLenum pname, const GLint* params);
void d_glTexSubImage2D_with_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLintptr pixels);
void d_glUniform1fv(void *context, GLint location, GLsizei count, const GLfloat* value);
void d_glUniform1iv(void *context, GLint location, GLsizei count, const GLint* value);
void d_glUniform2fv(void *context, GLint location, GLsizei count, const GLfloat* value);
void d_glUniform2iv(void *context, GLint location, GLsizei count, const GLint* value);
void d_glUniform3fv(void *context, GLint location, GLsizei count, const GLfloat* value);
void d_glUniform3iv(void *context, GLint location, GLsizei count, const GLint* value);
void d_glUniform4fv(void *context, GLint location, GLsizei count, const GLfloat* value);
void d_glUniform4iv(void *context, GLint location, GLsizei count, const GLint* value);
void d_glVertexAttrib1fv(void *context, GLuint index, const GLfloat* v);
void d_glVertexAttrib2fv(void *context, GLuint index, const GLfloat* v);
void d_glVertexAttrib3fv(void *context, GLuint index, const GLfloat* v);
void d_glVertexAttrib4fv(void *context, GLuint index, const GLfloat* v);
void d_glVertexAttribPointer_with_bound(void *context, GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, GLintptr pointer);
void d_glVertexAttribPointer_offset(void *context, GLuint index, GLuint size, GLenum type, GLboolean normalized, GLsizei stride, GLuint index_father, GLintptr offset);
void d_glDrawRangeElements_with_bound(void *context, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, GLsizeiptr indices);
void d_glTexImage3D_with_bound(void *context, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, GLintptr pixels);
void d_glTexSubImage3D_with_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLintptr pixels);
void d_glCompressedTexImage3D_with_bound(void *context, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, GLintptr data);
void d_glCompressedTexSubImage3D_with_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, GLintptr data);
void d_glCompressedTexImage2D_with_bound(void *context, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, GLintptr data);
void d_glDeleteQueries(void *context, GLsizei n, const GLuint* ids);
void d_glDrawBuffers(void *context, GLsizei n, const GLenum* bufs);
void d_glUniformMatrix2fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix3fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix4fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix2x3fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix3x2fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix2x4fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix4x2fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix3x4fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glUniformMatrix4x3fv(void *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glDeleteVertexArrays_origin(void *context, GLsizei n, const GLuint* arrays);
void d_glVertexAttribIPointer_with_bound(void *context, GLuint index, GLint size, GLenum type, GLsizei stride, GLintptr pointer);
void d_glVertexAttribIPointer_offset(void *context, GLuint index, GLint size, GLenum type, GLsizei stride, GLuint index_father, GLintptr offset);
void d_glVertexAttribI4iv(void *context, GLuint index, const GLint* v);
void d_glVertexAttribI4uiv(void *context, GLuint index, const GLuint* v);
void d_glUniform1uiv(void *context, GLint location, GLsizei count, const GLuint* value);
void d_glUniform2uiv(void *context, GLint location, GLsizei count, const GLuint* value);
void d_glUniform3uiv(void *context, GLint location, GLsizei count, const GLuint* value);
void d_glUniform4uiv(void *context, GLint location, GLsizei count, const GLuint* value);
void d_glClearBufferiv(void *context, GLenum buffer, GLint drawbuffer, const GLint* value);
void d_glClearBufferuiv(void *context, GLenum buffer, GLint drawbuffer, const GLuint* value);
void d_glClearBufferfv(void *context, GLenum buffer, GLint drawbuffer, const GLfloat* value);
void d_glDrawElementsInstanced_with_bound(void *context, GLenum mode, GLsizei count, GLenum type, GLsizeiptr indices, GLsizei instancecount);
void d_glDeleteSamplers(void *context, GLsizei count, const GLuint* samplers);
void d_glSamplerParameteriv(void *context, GLuint sampler, GLenum pname, const GLint* param);
void d_glSamplerParameterfv(void *context, GLuint sampler, GLenum pname, const GLfloat* param);
void d_glDeleteTransformFeedbacks(void *context, GLsizei n, const GLuint* ids);
void d_glProgramBinary(void *context, GLuint program, GLenum binaryFormat, const void* binary, GLsizei length);
void d_glInvalidateFramebuffer(void *context, GLenum target, GLsizei numAttachments, const GLenum* attachments);
void d_glInvalidateSubFramebuffer(void *context, GLenum target, GLsizei numAttachments, const GLenum* attachments, GLint x, GLint y, GLsizei width, GLsizei height);
void d_glClipPlanexOES(void *context, GLenum plane, const GLfixed* equation);
void d_glFogxvOES(void *context, GLenum pname, const GLfixed* param);
void d_glLightModelxvOES(void *context, GLenum pname, const GLfixed* param);
void d_glLightxvOES(void *context, GLenum light, GLenum pname, const GLfixed* params);
void d_glLoadMatrixxOES(void *context, const GLfixed* m);
void d_glMaterialxvOES(void *context, GLenum face, GLenum pname, const GLfixed* param);
void d_glMultMatrixxOES(void *context, const GLfixed* m);
void d_glPointParameterxvOES(void *context, GLenum pname, const GLfixed* params);
void d_glTexEnvxvOES(void *context, GLenum target, GLenum pname, const GLfixed* params);
void d_glClipPlanefOES(void *context, GLenum plane, const GLfloat* equation);
void d_glTexGenxvOES(void *context, GLenum coord, GLenum pname, const GLfixed* params);
void d_glDeleteProgramPipelines(void *context, GLsizei n, const GLuint* pipelines);
void d_glProgramUniform1iv(void *context, GLuint program, GLint location, GLsizei count, const GLint* value);
void d_glProgramUniform2iv(void *context, GLuint program, GLint location, GLsizei count, const GLint* value);
void d_glProgramUniform3iv(void *context, GLuint program, GLint location, GLsizei count, const GLint* value);
void d_glProgramUniform4iv(void *context, GLuint program, GLint location, GLsizei count, const GLint* value);
void d_glProgramUniform1uiv(void *context, GLuint program, GLint location, GLsizei count, const GLuint* value);
void d_glProgramUniform2uiv(void *context, GLuint program, GLint location, GLsizei count, const GLuint* value);
void d_glProgramUniform3uiv(void *context, GLuint program, GLint location, GLsizei count, const GLuint* value);
void d_glProgramUniform4uiv(void *context, GLuint program, GLint location, GLsizei count, const GLuint* value);
void d_glProgramUniform1fv(void *context, GLuint program, GLint location, GLsizei count, const GLfloat* value);
void d_glProgramUniform2fv(void *context, GLuint program, GLint location, GLsizei count, const GLfloat* value);
void d_glProgramUniform3fv(void *context, GLuint program, GLint location, GLsizei count, const GLfloat* value);
void d_glProgramUniform4fv(void *context, GLuint program, GLint location, GLsizei count, const GLfloat* value);
void d_glProgramUniformMatrix2fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix3fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix4fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix2x3fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix3x2fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix2x4fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix4x2fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix3x4fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glProgramUniformMatrix4x3fv(void *context, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
void d_glDeleteSync(void *context, GLsync sync);
void d_glWaitSync(void *context, GLsync sync, GLbitfield flags, GLuint64 timeout);
void d_glBindAttribLocation(void *context, GLuint program, GLuint index, const GLchar* name);
void d_glMapBufferRange_write(void *context, GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
GLboolean d_glUnmapBuffer_special(void *context, GLenum target);
void d_glTestIntAsyn(void *context, GLint a, GLuint b, GLfloat c, GLdouble d);
void d_glPrintfAsyn(void *context, GLint a, GLuint size, GLdouble c, const GLchar* out_string);
void d_glDrawElements_without_bound(void *context, GLenum mode, GLsizei count, GLenum type, const void* indices);
void d_glVertexAttribIPointer_without_bound(void *context, GLuint index, GLint size, GLenum type, GLsizei stride, GLuint offset, GLsizei length, const void* pointer);
void d_glVertexAttribPointer_without_bound(void *context, GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, GLuint offset, GLuint length, const void* pointer);
void d_glDrawElementsInstanced_without_bound(void *context, GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instancecount);
void d_glBufferData_custom(void *context, GLenum target, GLsizeiptr size, const void* data, GLenum usage);
void d_glBufferSubData_custom(void *context, GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
void d_glCompressedTexImage2D_without_bound(void *context, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data);
void d_glCompressedTexSubImage2D_without_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data);
void d_glTexImage2D_without_bound(void *context, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels);
void d_glDrawRangeElements_without_bound(void *context, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void* indices);
void d_glCompressedTexImage3D_without_bound(void *context, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void* data);
void d_glCompressedTexSubImage3D_without_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void* data);
void d_glTexSubImage2D_without_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels);
void d_glTexImage3D_without_bound(void *context, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void* pixels);
void d_glTexSubImage3D_without_bound(void *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void* pixels);
void d_glFlushMappedBufferRange_special(void *context, GLenum target, GLintptr offset, GLsizeiptr length, const void* data);
void d_glPrintf(void *context, GLint buf_len, const GLchar* out_string);
void d_glGenBuffers_origin(void *context, GLsizei n, GLuint* buffers);
void d_glGenBuffers(void *context, GLsizei n, GLuint* buffers);
void d_glGenFramebuffers_origin(void *context, GLsizei n, GLuint* framebuffers);
void d_glGenFramebuffers(void *context, GLsizei n, GLuint* framebuffers);
void d_glGenRenderbuffers_origin(void *context, GLsizei n, GLuint* renderbuffers);
void d_glGenRenderbuffers(void *context, GLsizei n, GLuint* renderbuffers);
void d_glGenTextures_origin(void *context, GLsizei n, GLuint* textures);
void d_glGenTextures(void *context, GLsizei n, GLuint* textures);
void d_glGenQueries_origin(void *context, GLsizei n, GLuint* ids);
void d_glGenQueries(void *context, GLsizei n, GLuint* ids);
void d_glGenVertexArrays_origin(void *context, GLsizei n, GLuint* arrays);
void d_glGenSamplers_origin(void *context, GLsizei count, GLuint* samplers);
void d_glGenSamplers(void *context, GLsizei count, GLuint* samplers);
void d_glGenTransformFeedbacks_origin(void *context, GLsizei n, GLuint* ids);
void d_glGenTransformFeedbacks(void *context, GLsizei n, GLuint* ids);
void d_glGenProgramPipelines_origin(void *context, GLsizei n, GLuint* pipelines);
void d_glGenProgramPipelines(void *context, GLsizei n, GLuint* pipelines);
GLuint d_glCreateProgram_origin(void *context);
GLuint d_glCreateProgram(void *context);
GLuint d_glCreateShader_origin(void *context, GLenum type);
GLuint d_glCreateShader(void *context, GLenum type);

#endif