// Copyright (C) 2018 The Android Open Source Project
// Copyright (C) 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated module goldfish_vk_reserved_marshaling
//
// (header) generated by codegen/vulkan/vulkan-docs-next/scripts/genvk.py -registry
// codegen/vulkan/vulkan-docs-next/xml/vk.xml -registryGfxstream
// codegen/vulkan/vulkan-docs-next/xml/vk_gfxstream.xml cereal -o host/vulkan/cereal
//
// Please do not modify directly;
// re-run gfxstream-protocols/scripts/generate-vulkan-sources.sh,
// or directly from Python by defining:
// VULKAN_REGISTRY_XML_DIR : Directory containing vk.xml
// VULKAN_REGISTRY_SCRIPTS_DIR : Directory containing genvk.py
// CEREAL_OUTPUT_DIR: Where to put the generated sources.
//
// python3 $VULKAN_REGISTRY_SCRIPTS_DIR/genvk.py -registry $VULKAN_REGISTRY_XML_DIR/vk.xml cereal -o
// $CEREAL_OUTPUT_DIR
//
#pragma once
#include <vulkan/vulkan.h>

#include "express_vk_private_defs.h"
#include "express_vk_android_native_buffer_gfxstream.h"

#ifdef VK_VERSION_1_0
void decode_from_stream_VkPhysicalDeviceSurfaceInfo2KHR(VkStructureType rootType,
                                                        VkPhysicalDeviceSurfaceInfo2KHR* forUnmarshaling,
                                                        uint8_t** ptr);
void decode_from_stream_VkDisplayPropertiesKHR(VkStructureType rootType,
                                               VkDisplayPropertiesKHR* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkDisplayPlanePropertiesKHR(VkStructureType rootType,
                                                    VkDisplayPlanePropertiesKHR* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkDisplayPlaneProperties2KHR(VkStructureType rootType,
                                                     VkDisplayPlaneProperties2KHR* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkDisplayProperties2KHR(VkStructureType rootType,
                                                VkDisplayProperties2KHR* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkDisplayPlaneCapabilities2KHR(VkStructureType rootType,
                                                       VkDisplayPlaneCapabilities2KHR* forUnmarshaling,
                                                       uint8_t** ptr);

void decode_from_stream_VkDisplaySurfaceCreateInfoKHR(VkStructureType rootType,
                                                      VkDisplaySurfaceCreateInfoKHR* forUnmarshaling,
                                                      uint8_t** ptr);

void decode_from_stream_VkDisplayModeCreateInfoKHR(VkStructureType rootType,
                                                   VkDisplayModeCreateInfoKHR* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkDisplayPlaneCapabilitiesKHR(VkStructureType rootType,
                                                      VkDisplayPlaneCapabilitiesKHR* forUnmarshaling,
                                                      uint8_t** ptr);

void decode_from_stream_VkDisplayModeParametersKHR(VkStructureType rootType,
                                                   VkDisplayModeParametersKHR* forUnmarshaling,
                                                   uint8_t** ptr);


void decode_from_stream_VkDisplayPlaneInfo2KHR(VkStructureType rootType,
                                               VkDisplayPlaneInfo2KHR* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkExtent2D(VkStructureType rootType,
                                  VkExtent2D* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExtent3D(VkStructureType rootType,
                                  VkExtent3D* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkOffset2D(VkStructureType rootType,
                                  VkOffset2D* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkOffset3D(VkStructureType rootType,
                                  VkOffset3D* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRect2D(VkStructureType rootType,
                                VkRect2D* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBaseInStructure(VkStructureType rootType,
                                         VkBaseInStructure* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBaseOutStructure(VkStructureType rootType,
                                          VkBaseOutStructure* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferMemoryBarrier(VkStructureType rootType,
                                             VkBufferMemoryBarrier* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDispatchIndirectCommand(VkStructureType rootType,
                                                 VkDispatchIndirectCommand* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkDrawIndexedIndirectCommand(VkStructureType rootType,
                                                    VkDrawIndexedIndirectCommand* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkDrawIndirectCommand(VkStructureType rootType,
                                             VkDrawIndirectCommand* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageSubresourceRange(VkStructureType rootType,
                                               VkImageSubresourceRange* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkImageMemoryBarrier(VkStructureType rootType,
                                            VkImageMemoryBarrier* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryBarrier(VkStructureType rootType,
                                       VkMemoryBarrier* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineCacheHeaderVersionOne(
    VkStructureType rootType,
    VkPipelineCacheHeaderVersionOne* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkAllocationCallbacks(VkStructureType rootType,
                                             VkAllocationCallbacks* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkApplicationInfo(VkStructureType rootType,
                                         VkApplicationInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkFormatProperties(VkStructureType rootType,
                                          VkFormatProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageFormatProperties(VkStructureType rootType,
                                               VkImageFormatProperties* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkInstanceCreateInfo(VkStructureType rootType,
                                            VkInstanceCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryHeap(VkStructureType rootType,
                                    VkMemoryHeap* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryType(VkStructureType rootType,
                                    VkMemoryType* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceFeatures(VkStructureType rootType,
                                                VkPhysicalDeviceFeatures* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceLimits(VkStructureType rootType,
                                              VkPhysicalDeviceLimits* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMemoryProperties(
    VkStructureType rootType,
    VkPhysicalDeviceMemoryProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSparseProperties(
    VkStructureType rootType,
    VkPhysicalDeviceSparseProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceProperties(VkStructureType rootType,
                                                  VkPhysicalDeviceProperties* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkQueueFamilyProperties(VkStructureType rootType,
                                               VkQueueFamilyProperties* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkDeviceQueueCreateInfo(VkStructureType rootType,
                                               VkDeviceQueueCreateInfo* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkDeviceCreateInfo(VkStructureType rootType,
                                          VkDeviceCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExtensionProperties(VkStructureType rootType,
                                             VkExtensionProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkLayerProperties(VkStructureType rootType,
                                         VkLayerProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubmitInfo(VkStructureType rootType,
                                    VkSubmitInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMappedMemoryRange(VkStructureType rootType,
                                           VkMappedMemoryRange* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryAllocateInfo(VkStructureType rootType,
                                            VkMemoryAllocateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryRequirements(VkStructureType rootType,
                                            VkMemoryRequirements* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSparseMemoryBind(VkStructureType rootType,
                                          VkSparseMemoryBind* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSparseBufferMemoryBindInfo(VkStructureType rootType,
                                                    VkSparseBufferMemoryBindInfo* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkSparseImageOpaqueMemoryBindInfo(
    VkStructureType rootType,
    VkSparseImageOpaqueMemoryBindInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageSubresource(VkStructureType rootType,
                                          VkImageSubresource* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSparseImageMemoryBind(VkStructureType rootType,
                                               VkSparseImageMemoryBind* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkSparseImageMemoryBindInfo(VkStructureType rootType,
                                                   VkSparseImageMemoryBindInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkBindSparseInfo(VkStructureType rootType,
                                        VkBindSparseInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSparseImageFormatProperties(VkStructureType rootType,
                                                     VkSparseImageFormatProperties* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkSparseImageMemoryRequirements(
    VkStructureType rootType,
    VkSparseImageMemoryRequirements* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkFenceCreateInfo(VkStructureType rootType,
                                         VkFenceCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSemaphoreCreateInfo(VkStructureType rootType,
                                             VkSemaphoreCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkEventCreateInfo(VkStructureType rootType,
                                         VkEventCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkQueryPoolCreateInfo(VkStructureType rootType,
                                             VkQueryPoolCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferCreateInfo(VkStructureType rootType,
                                          VkBufferCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferViewCreateInfo(VkStructureType rootType,
                                              VkBufferViewCreateInfo* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkImageCreateInfo(VkStructureType rootType,
                                         VkImageCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubresourceLayout(VkStructureType rootType,
                                           VkSubresourceLayout* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkComponentMapping(VkStructureType rootType,
                                          VkComponentMapping* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageViewCreateInfo(VkStructureType rootType,
                                             VkImageViewCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkShaderModuleCreateInfo(VkStructureType rootType,
                                                VkShaderModuleCreateInfo* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkPipelineCacheCreateInfo(VkStructureType rootType,
                                                 VkPipelineCacheCreateInfo* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkSpecializationMapEntry(VkStructureType rootType,
                                                VkSpecializationMapEntry* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkSpecializationInfo(VkStructureType rootType,
                                            VkSpecializationInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineShaderStageCreateInfo(
    VkStructureType rootType,
    VkPipelineShaderStageCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkComputePipelineCreateInfo(VkStructureType rootType,
                                                   VkComputePipelineCreateInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkVertexInputBindingDescription(
    VkStructureType rootType,
    VkVertexInputBindingDescription* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkVertexInputAttributeDescription(
    VkStructureType rootType,
    VkVertexInputAttributeDescription* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineVertexInputStateCreateInfo(
    VkStructureType rootType,
    VkPipelineVertexInputStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineInputAssemblyStateCreateInfo(
    VkStructureType rootType,
    VkPipelineInputAssemblyStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineTessellationStateCreateInfo(
    VkStructureType rootType,
    VkPipelineTessellationStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkViewport(VkStructureType rootType,
                                  VkViewport* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineViewportStateCreateInfo(
    VkStructureType rootType,
    VkPipelineViewportStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineRasterizationStateCreateInfo(
    VkStructureType rootType,
    VkPipelineRasterizationStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineMultisampleStateCreateInfo(
    VkStructureType rootType,
    VkPipelineMultisampleStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkStencilOpState(VkStructureType rootType,
                                        VkStencilOpState* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineDepthStencilStateCreateInfo(
    VkStructureType rootType,
    VkPipelineDepthStencilStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineColorBlendAttachmentState(
    VkStructureType rootType,
    VkPipelineColorBlendAttachmentState* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineColorBlendStateCreateInfo(
    VkStructureType rootType,
    VkPipelineColorBlendStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineDynamicStateCreateInfo(
    VkStructureType rootType,
    VkPipelineDynamicStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkGraphicsPipelineCreateInfo(VkStructureType rootType,
                                                    VkGraphicsPipelineCreateInfo* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkPushConstantRange(VkStructureType rootType,
                                           VkPushConstantRange* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineLayoutCreateInfo(VkStructureType rootType,
                                                  VkPipelineLayoutCreateInfo* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkSamplerCreateInfo(VkStructureType rootType,
                                           VkSamplerCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCopyDescriptorSet(VkStructureType rootType,
                                           VkCopyDescriptorSet* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorBufferInfo(VkStructureType rootType,
                                              VkDescriptorBufferInfo* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkDescriptorImageInfo(VkStructureType rootType,
                                             VkDescriptorImageInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorPoolSize(VkStructureType rootType,
                                            VkDescriptorPoolSize* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorPoolCreateInfo(VkStructureType rootType,
                                                  VkDescriptorPoolCreateInfo* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkDescriptorSetAllocateInfo(VkStructureType rootType,
                                                   VkDescriptorSetAllocateInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkDescriptorSetLayoutBinding(VkStructureType rootType,
                                                    VkDescriptorSetLayoutBinding* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkDescriptorSetLayoutCreateInfo(
    VkStructureType rootType,
    VkDescriptorSetLayoutCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkWriteDescriptorSet(VkStructureType rootType,
                                            VkWriteDescriptorSet* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkAttachmentDescription(VkStructureType rootType,
                                               VkAttachmentDescription* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkAttachmentReference(VkStructureType rootType,
                                             VkAttachmentReference* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkFramebufferCreateInfo(VkStructureType rootType,
                                               VkFramebufferCreateInfo* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkSubpassDescription(VkStructureType rootType,
                                            VkSubpassDescription* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubpassDependency(VkStructureType rootType,
                                           VkSubpassDependency* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderPassCreateInfo(VkStructureType rootType,
                                              VkRenderPassCreateInfo* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkCommandPoolCreateInfo(VkStructureType rootType,
                                               VkCommandPoolCreateInfo* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkCommandBufferAllocateInfo(VkStructureType rootType,
                                                   VkCommandBufferAllocateInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkCommandBufferInheritanceInfo(
    VkStructureType rootType,
    VkCommandBufferInheritanceInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCommandBufferBeginInfo(VkStructureType rootType,
                                                VkCommandBufferBeginInfo* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkBufferCopy(VkStructureType rootType,
                                    VkBufferCopy* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageSubresourceLayers(VkStructureType rootType,
                                                VkImageSubresourceLayers* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkBufferImageCopy(VkStructureType rootType,
                                         VkBufferImageCopy* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkClearColorValue(VkStructureType rootType,
                                         VkClearColorValue* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkClearDepthStencilValue(VkStructureType rootType,
                                                VkClearDepthStencilValue* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkClearValue(VkStructureType rootType,
                                    VkClearValue* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkClearAttachment(VkStructureType rootType,
                                         VkClearAttachment* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkClearRect(VkStructureType rootType,
                                   VkClearRect* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageBlit(VkStructureType rootType,
                                   VkImageBlit* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageCopy(VkStructureType rootType,
                                   VkImageCopy* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageResolve(VkStructureType rootType,
                                      VkImageResolve* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderPassBeginInfo(VkStructureType rootType,
                                             VkRenderPassBeginInfo* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_VERSION_1_1
void decode_from_stream_VkPhysicalDeviceSubgroupProperties(
    VkStructureType rootType,
    VkPhysicalDeviceSubgroupProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBindBufferMemoryInfo(VkStructureType rootType,
                                              VkBindBufferMemoryInfo* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkBindImageMemoryInfo(VkStructureType rootType,
                                             VkBindImageMemoryInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDevice16BitStorageFeatures(
    VkStructureType rootType,
    VkPhysicalDevice16BitStorageFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryDedicatedRequirements(VkStructureType rootType,
                                                     VkMemoryDedicatedRequirements* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkMemoryDedicatedAllocateInfo(VkStructureType rootType,
                                                     VkMemoryDedicatedAllocateInfo* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkMemoryAllocateFlagsInfo(VkStructureType rootType,
                                                 VkMemoryAllocateFlagsInfo* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkDeviceGroupRenderPassBeginInfo(
    VkStructureType rootType,
    VkDeviceGroupRenderPassBeginInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceGroupCommandBufferBeginInfo(
    VkStructureType rootType,
    VkDeviceGroupCommandBufferBeginInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceGroupSubmitInfo(VkStructureType rootType,
                                               VkDeviceGroupSubmitInfo* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkDeviceGroupBindSparseInfo(VkStructureType rootType,
                                                   VkDeviceGroupBindSparseInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkBindBufferMemoryDeviceGroupInfo(
    VkStructureType rootType,
    VkBindBufferMemoryDeviceGroupInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBindImageMemoryDeviceGroupInfo(
    VkStructureType rootType,
    VkBindImageMemoryDeviceGroupInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceGroupProperties(
    VkStructureType rootType,
    VkPhysicalDeviceGroupProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceGroupDeviceCreateInfo(VkStructureType rootType,
                                                     VkDeviceGroupDeviceCreateInfo* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkBufferMemoryRequirementsInfo2(
    VkStructureType rootType,
    VkBufferMemoryRequirementsInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageMemoryRequirementsInfo2(
    VkStructureType rootType,
    VkImageMemoryRequirementsInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageSparseMemoryRequirementsInfo2(
    VkStructureType rootType,
    VkImageSparseMemoryRequirementsInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryRequirements2(VkStructureType rootType,
                                             VkMemoryRequirements2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSparseImageMemoryRequirements2(
    VkStructureType rootType,
    VkSparseImageMemoryRequirements2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceFeatures2(VkStructureType rootType,
                                                 VkPhysicalDeviceFeatures2* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceProperties2(VkStructureType rootType,
                                                   VkPhysicalDeviceProperties2* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkFormatProperties2(VkStructureType rootType,
                                           VkFormatProperties2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageFormatProperties2(VkStructureType rootType,
                                                VkImageFormatProperties2* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceImageFormatInfo2(
    VkStructureType rootType,
    VkPhysicalDeviceImageFormatInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkQueueFamilyProperties2(VkStructureType rootType,
                                                VkQueueFamilyProperties2* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMemoryProperties2(
    VkStructureType rootType,
    VkPhysicalDeviceMemoryProperties2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSparseImageFormatProperties2(
    VkStructureType rootType,
    VkSparseImageFormatProperties2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSparseImageFormatInfo2(
    VkStructureType rootType,
    VkPhysicalDeviceSparseImageFormatInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDevicePointClippingProperties(
    VkStructureType rootType,
    VkPhysicalDevicePointClippingProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkInputAttachmentAspectReference(
    VkStructureType rootType,
    VkInputAttachmentAspectReference* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderPassInputAttachmentAspectCreateInfo(
    VkStructureType rootType,
    VkRenderPassInputAttachmentAspectCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageViewUsageCreateInfo(VkStructureType rootType,
                                                  VkImageViewUsageCreateInfo* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkPipelineTessellationDomainOriginStateCreateInfo(
    VkStructureType rootType,
    VkPipelineTessellationDomainOriginStateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderPassMultiviewCreateInfo(
    VkStructureType rootType,
    VkRenderPassMultiviewCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMultiviewFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceMultiviewFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMultiviewProperties(
    VkStructureType rootType,
    VkPhysicalDeviceMultiviewProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceVariablePointersFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceVariablePointersFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceProtectedMemoryFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceProtectedMemoryFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceProtectedMemoryProperties(
    VkStructureType rootType,
    VkPhysicalDeviceProtectedMemoryProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceQueueInfo2(VkStructureType rootType,
                                          VkDeviceQueueInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkProtectedSubmitInfo(VkStructureType rootType,
                                             VkProtectedSubmitInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSamplerYcbcrConversionCreateInfo(
    VkStructureType rootType,
    VkSamplerYcbcrConversionCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSamplerYcbcrConversionInfo(VkStructureType rootType,
                                                    VkSamplerYcbcrConversionInfo* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkBindImagePlaneMemoryInfo(VkStructureType rootType,
                                                  VkBindImagePlaneMemoryInfo* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkImagePlaneMemoryRequirementsInfo(
    VkStructureType rootType,
    VkImagePlaneMemoryRequirementsInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSamplerYcbcrConversionFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceSamplerYcbcrConversionFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSamplerYcbcrConversionImageFormatProperties(
    VkStructureType rootType,
    VkSamplerYcbcrConversionImageFormatProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorUpdateTemplateEntry(
    VkStructureType rootType,
    VkDescriptorUpdateTemplateEntry* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorUpdateTemplateCreateInfo(
    VkStructureType rootType,
    VkDescriptorUpdateTemplateCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExternalMemoryProperties(VkStructureType rootType,
                                                  VkExternalMemoryProperties* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceExternalImageFormatInfo(
    VkStructureType rootType,
    VkPhysicalDeviceExternalImageFormatInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExternalImageFormatProperties(
    VkStructureType rootType,
    VkExternalImageFormatProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceExternalBufferInfo(
    VkStructureType rootType,
    VkPhysicalDeviceExternalBufferInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExternalBufferProperties(VkStructureType rootType,
                                                  VkExternalBufferProperties* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceIDProperties(VkStructureType rootType,
                                                    VkPhysicalDeviceIDProperties* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkExternalMemoryImageCreateInfo(
    VkStructureType rootType,
    VkExternalMemoryImageCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExternalMemoryBufferCreateInfo(
    VkStructureType rootType,
    VkExternalMemoryBufferCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExportMemoryAllocateInfo(VkStructureType rootType,
                                                  VkExportMemoryAllocateInfo* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceExternalFenceInfo(
    VkStructureType rootType,
    VkPhysicalDeviceExternalFenceInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExternalFenceProperties(VkStructureType rootType,
                                                 VkExternalFenceProperties* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkExportFenceCreateInfo(VkStructureType rootType,
                                               VkExportFenceCreateInfo* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkExportSemaphoreCreateInfo(VkStructureType rootType,
                                                   VkExportSemaphoreCreateInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceExternalSemaphoreInfo(
    VkStructureType rootType,
    VkPhysicalDeviceExternalSemaphoreInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkExternalSemaphoreProperties(VkStructureType rootType,
                                                     VkExternalSemaphoreProperties* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMaintenance3Properties(
    VkStructureType rootType,
    VkPhysicalDeviceMaintenance3Properties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorSetLayoutSupport(VkStructureType rootType,
                                                    VkDescriptorSetLayoutSupport* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderDrawParametersFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceShaderDrawParametersFeatures* forUnmarshaling, uint8_t** ptr);


#endif
#ifdef VK_VERSION_1_2
void decode_from_stream_VkPhysicalDeviceVulkan11Features(
    VkStructureType rootType,
    VkPhysicalDeviceVulkan11Features* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceVulkan11Properties(
    VkStructureType rootType,
    VkPhysicalDeviceVulkan11Properties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceVulkan12Features(
    VkStructureType rootType,
    VkPhysicalDeviceVulkan12Features* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkConformanceVersion(VkStructureType rootType,
                                            VkConformanceVersion* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceVulkan12Properties(
    VkStructureType rootType,
    VkPhysicalDeviceVulkan12Properties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageFormatListCreateInfo(VkStructureType rootType,
                                                   VkImageFormatListCreateInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkAttachmentDescription2(VkStructureType rootType,
                                                VkAttachmentDescription2* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkAttachmentReference2(VkStructureType rootType,
                                              VkAttachmentReference2* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkSubpassDescription2(VkStructureType rootType,
                                             VkSubpassDescription2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubpassDependency2(VkStructureType rootType,
                                            VkSubpassDependency2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderPassCreateInfo2(VkStructureType rootType,
                                               VkRenderPassCreateInfo2* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkSubpassBeginInfo(VkStructureType rootType,
                                          VkSubpassBeginInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubpassEndInfo(VkStructureType rootType,
                                        VkSubpassEndInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDevice8BitStorageFeatures(
    VkStructureType rootType,
    VkPhysicalDevice8BitStorageFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceDriverProperties(
    VkStructureType rootType,
    VkPhysicalDeviceDriverProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderAtomicInt64Features(
    VkStructureType rootType,
    VkPhysicalDeviceShaderAtomicInt64Features* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderFloat16Int8Features(
    VkStructureType rootType,
    VkPhysicalDeviceShaderFloat16Int8Features* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceFloatControlsProperties(
    VkStructureType rootType,
    VkPhysicalDeviceFloatControlsProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorSetLayoutBindingFlagsCreateInfo(
    VkStructureType rootType,
    VkDescriptorSetLayoutBindingFlagsCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceDescriptorIndexingFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceDescriptorIndexingFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceDescriptorIndexingProperties(
    VkStructureType rootType,
    VkPhysicalDeviceDescriptorIndexingProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorSetVariableDescriptorCountAllocateInfo(
    VkStructureType rootType,
    VkDescriptorSetVariableDescriptorCountAllocateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorSetVariableDescriptorCountLayoutSupport(
    VkStructureType rootType,
    VkDescriptorSetVariableDescriptorCountLayoutSupport* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubpassDescriptionDepthStencilResolve(
    VkStructureType rootType,
    VkSubpassDescriptionDepthStencilResolve* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceDepthStencilResolveProperties(
    VkStructureType rootType,
    VkPhysicalDeviceDepthStencilResolveProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceScalarBlockLayoutFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceScalarBlockLayoutFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageStencilUsageCreateInfo(VkStructureType rootType,
                                                     VkImageStencilUsageCreateInfo* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkSamplerReductionModeCreateInfo(
    VkStructureType rootType,
    VkSamplerReductionModeCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSamplerFilterMinmaxProperties(
    VkStructureType rootType,
    VkPhysicalDeviceSamplerFilterMinmaxProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceVulkanMemoryModelFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceVulkanMemoryModelFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceImagelessFramebufferFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceImagelessFramebufferFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkFramebufferAttachmentImageInfo(
    VkStructureType rootType,
    VkFramebufferAttachmentImageInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkFramebufferAttachmentsCreateInfo(
    VkStructureType rootType,
    VkFramebufferAttachmentsCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderPassAttachmentBeginInfo(
    VkStructureType rootType,
    VkRenderPassAttachmentBeginInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceUniformBufferStandardLayoutFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceUniformBufferStandardLayoutFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkAttachmentReferenceStencilLayout(
    VkStructureType rootType,
    VkAttachmentReferenceStencilLayout* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkAttachmentDescriptionStencilLayout(
    VkStructureType rootType,
    VkAttachmentDescriptionStencilLayout* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceHostQueryResetFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceHostQueryResetFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceTimelineSemaphoreFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceTimelineSemaphoreFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceTimelineSemaphoreProperties(
    VkStructureType rootType,
    VkPhysicalDeviceTimelineSemaphoreProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSemaphoreTypeCreateInfo(VkStructureType rootType,
                                                 VkSemaphoreTypeCreateInfo* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkTimelineSemaphoreSubmitInfo(VkStructureType rootType,
                                                     VkTimelineSemaphoreSubmitInfo* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkSemaphoreWaitInfo(VkStructureType rootType,
                                           VkSemaphoreWaitInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSemaphoreSignalInfo(VkStructureType rootType,
                                             VkSemaphoreSignalInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceBufferDeviceAddressFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceBufferDeviceAddressFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferDeviceAddressInfo(VkStructureType rootType,
                                                 VkBufferDeviceAddressInfo* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkBufferOpaqueCaptureAddressCreateInfo(
    VkStructureType rootType,
    VkBufferOpaqueCaptureAddressCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryOpaqueCaptureAddressAllocateInfo(
    VkStructureType rootType,
    VkMemoryOpaqueCaptureAddressAllocateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceMemoryOpaqueCaptureAddressInfo(
    VkStructureType rootType,
    VkDeviceMemoryOpaqueCaptureAddressInfo* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_VERSION_1_3
void decode_from_stream_VkPhysicalDeviceVulkan13Features(
    VkStructureType rootType,
    VkPhysicalDeviceVulkan13Features* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceVulkan13Properties(
    VkStructureType rootType,
    VkPhysicalDeviceVulkan13Properties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineCreationFeedback(VkStructureType rootType,
                                                  VkPipelineCreationFeedback* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkPipelineCreationFeedbackCreateInfo(
    VkStructureType rootType,
    VkPipelineCreationFeedbackCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderTerminateInvocationFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceShaderTerminateInvocationFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceToolProperties(
    VkStructureType rootType,
    VkPhysicalDeviceToolProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDevicePrivateDataFeatures(
    VkStructureType rootType,
    VkPhysicalDevicePrivateDataFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDevicePrivateDataCreateInfo(VkStructureType rootType,
                                                     VkDevicePrivateDataCreateInfo* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkPrivateDataSlotCreateInfo(VkStructureType rootType,
                                                   VkPrivateDataSlotCreateInfo* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkPhysicalDevicePipelineCreationCacheControlFeatures(
    VkStructureType rootType,
    VkPhysicalDevicePipelineCreationCacheControlFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryBarrier2(VkStructureType rootType,
                                        VkMemoryBarrier2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferMemoryBarrier2(VkStructureType rootType,
                                              VkBufferMemoryBarrier2* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkImageMemoryBarrier2(VkStructureType rootType,
                                             VkImageMemoryBarrier2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDependencyInfo(VkStructureType rootType,
                                        VkDependencyInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSemaphoreSubmitInfo(VkStructureType rootType,
                                             VkSemaphoreSubmitInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCommandBufferSubmitInfo(VkStructureType rootType,
                                                 VkCommandBufferSubmitInfo* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkSubmitInfo2(VkStructureType rootType,
                                     VkSubmitInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSynchronization2Features(
    VkStructureType rootType,
    VkPhysicalDeviceSynchronization2Features* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceImageRobustnessFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceImageRobustnessFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferCopy2(VkStructureType rootType,
                                     VkBufferCopy2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCopyBufferInfo2(VkStructureType rootType,
                                         VkCopyBufferInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageCopy2(VkStructureType rootType,
                                    VkImageCopy2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCopyImageInfo2(VkStructureType rootType,
                                        VkCopyImageInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferImageCopy2(VkStructureType rootType,
                                          VkBufferImageCopy2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCopyBufferToImageInfo2(VkStructureType rootType,
                                                VkCopyBufferToImageInfo2* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkCopyImageToBufferInfo2(VkStructureType rootType,
                                                VkCopyImageToBufferInfo2* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkImageBlit2(VkStructureType rootType,
                                    VkImageBlit2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBlitImageInfo2(VkStructureType rootType,
                                        VkBlitImageInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageResolve2(VkStructureType rootType,
                                       VkImageResolve2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkResolveImageInfo2(VkStructureType rootType,
                                           VkResolveImageInfo2* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSubgroupSizeControlFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceSubgroupSizeControlFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceSubgroupSizeControlProperties(
    VkStructureType rootType,
    VkPhysicalDeviceSubgroupSizeControlProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineShaderStageRequiredSubgroupSizeCreateInfo(
    VkStructureType rootType,
    VkPipelineShaderStageRequiredSubgroupSizeCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceInlineUniformBlockFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceInlineUniformBlockFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceInlineUniformBlockProperties(
    VkStructureType rootType,
    VkPhysicalDeviceInlineUniformBlockProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkWriteDescriptorSetInlineUniformBlock(
    VkStructureType rootType,
    VkWriteDescriptorSetInlineUniformBlock* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDescriptorPoolInlineUniformBlockCreateInfo(
    VkStructureType rootType,
    VkDescriptorPoolInlineUniformBlockCreateInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceTextureCompressionASTCHDRFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceTextureCompressionASTCHDRFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderingAttachmentInfo(VkStructureType rootType,
                                                 VkRenderingAttachmentInfo* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkRenderingInfo(VkStructureType rootType,
                                       VkRenderingInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineRenderingCreateInfo(VkStructureType rootType,
                                                     VkPipelineRenderingCreateInfo* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceDynamicRenderingFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceDynamicRenderingFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCommandBufferInheritanceRenderingInfo(
    VkStructureType rootType,
    VkCommandBufferInheritanceRenderingInfo* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderIntegerDotProductFeatures(
    VkStructureType rootType,
    VkPhysicalDeviceShaderIntegerDotProductFeatures* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceShaderIntegerDotProductProperties(
    VkStructureType rootType,
    VkPhysicalDeviceShaderIntegerDotProductProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceTexelBufferAlignmentProperties(
    VkStructureType rootType,
    VkPhysicalDeviceTexelBufferAlignmentProperties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkFormatProperties3(VkStructureType rootType,
                                           VkFormatProperties3* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMaintenance4Features(
    VkStructureType rootType,
    VkPhysicalDeviceMaintenance4Features* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMaintenance4Properties(
    VkStructureType rootType,
    VkPhysicalDeviceMaintenance4Properties* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceBufferMemoryRequirements(
    VkStructureType rootType,
    VkDeviceBufferMemoryRequirements* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceImageMemoryRequirements(
    VkStructureType rootType,
    VkDeviceImageMemoryRequirements* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_swapchain
void decode_from_stream_VkSwapchainCreateInfoKHR(VkStructureType rootType,
                                                VkSwapchainCreateInfoKHR* forUnmarshaling,
                                                uint8_t** ptr);

void decode_from_stream_VkPresentInfoKHR(VkStructureType rootType,
                                        VkPresentInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageSwapchainCreateInfoKHR(VkStructureType rootType,
                                                     VkImageSwapchainCreateInfoKHR* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkBindImageMemorySwapchainInfoKHR(
    VkStructureType rootType,
    VkBindImageMemorySwapchainInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkAcquireNextImageInfoKHR(VkStructureType rootType,
                                                 VkAcquireNextImageInfoKHR* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkDeviceGroupPresentCapabilitiesKHR(
    VkStructureType rootType,
    VkDeviceGroupPresentCapabilitiesKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceGroupPresentInfoKHR(VkStructureType rootType,
                                                   VkDeviceGroupPresentInfoKHR* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkDeviceGroupSwapchainCreateInfoKHR(
    VkStructureType rootType,
    VkDeviceGroupSwapchainCreateInfoKHR* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_dynamic_rendering

void decode_from_stream_VkRenderingFragmentShadingRateAttachmentInfoKHR(
    VkStructureType rootType,
    VkRenderingFragmentShadingRateAttachmentInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderingFragmentDensityMapAttachmentInfoEXT(
    VkStructureType rootType,
    VkRenderingFragmentDensityMapAttachmentInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkAttachmentSampleCountInfoAMD(
    VkStructureType rootType,
    VkAttachmentSampleCountInfoAMD* forUnmarshaling, uint8_t** ptr);


void decode_from_stream_VkMultiviewPerViewAttributesInfoNVX(
    VkStructureType rootType,
    VkMultiviewPerViewAttributesInfoNVX* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_get_physical_device_properties2

#endif
#ifdef VK_KHR_external_memory_capabilities

#endif
#ifdef VK_KHR_external_memory

#endif
#ifdef VK_KHR_external_semaphore_capabilities

#endif
#ifdef VK_KHR_external_semaphore

#endif
#ifdef VK_KHR_external_semaphore_fd
void decode_from_stream_VkImportSemaphoreFdInfoKHR(VkStructureType rootType,
                                                  VkImportSemaphoreFdInfoKHR* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkSemaphoreGetFdInfoKHR(VkStructureType rootType,
                                               VkSemaphoreGetFdInfoKHR* forUnmarshaling,
                                               uint8_t** ptr);

#endif
#ifdef VK_KHR_shader_float16_int8

#endif
#ifdef VK_KHR_incremental_present
void decode_from_stream_VkRectLayerKHR(VkStructureType rootType,
                                      VkRectLayerKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPresentRegionKHR(VkStructureType rootType,
                                          VkPresentRegionKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPresentRegionsKHR(VkStructureType rootType,
                                           VkPresentRegionsKHR* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_descriptor_update_template

#endif
#ifdef VK_KHR_imageless_framebuffer

#endif
#ifdef VK_KHR_create_renderpass2

#endif
#ifdef VK_KHR_external_fence_capabilities

#endif
#ifdef VK_KHR_external_fence

#endif
#ifdef VK_KHR_external_fence_fd
void decode_from_stream_VkImportFenceFdInfoKHR(VkStructureType rootType,
                                              VkImportFenceFdInfoKHR* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkFenceGetFdInfoKHR(VkStructureType rootType,
                                           VkFenceGetFdInfoKHR* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_maintenance2

#endif
#ifdef VK_KHR_dedicated_allocation

#endif
#ifdef VK_KHR_get_memory_requirements2

#endif
#ifdef VK_KHR_image_format_list

#endif
#ifdef VK_KHR_sampler_ycbcr_conversion

#endif
#ifdef VK_KHR_bind_memory2

#endif
#ifdef VK_KHR_maintenance3

#endif
#ifdef VK_KHR_shader_subgroup_extended_types

#endif
#ifdef VK_KHR_vulkan_memory_model

#endif
#ifdef VK_KHR_shader_terminate_invocation

#endif
#ifdef VK_KHR_buffer_device_address

#endif
#ifdef VK_KHR_pipeline_executable_properties
void decode_from_stream_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR(
    VkStructureType rootType,
    VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineInfoKHR(VkStructureType rootType,
                                         VkPipelineInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineExecutablePropertiesKHR(
    VkStructureType rootType,
    VkPipelineExecutablePropertiesKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineExecutableInfoKHR(VkStructureType rootType,
                                                   VkPipelineExecutableInfoKHR* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkPipelineExecutableStatisticValueKHR(
    VkStructureType rootType,
    VkPipelineExecutableStatisticValueKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineExecutableStatisticKHR(
    VkStructureType rootType,
    VkPipelineExecutableStatisticKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineExecutableInternalRepresentationKHR(
    VkStructureType rootType,
    VkPipelineExecutableInternalRepresentationKHR* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_shader_integer_dot_product

#endif
#ifdef VK_KHR_pipeline_library
void decode_from_stream_VkPipelineLibraryCreateInfoKHR(
    VkStructureType rootType,
    VkPipelineLibraryCreateInfoKHR* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_synchronization2

void decode_from_stream_VkQueueFamilyCheckpointProperties2NV(
    VkStructureType rootType,
    VkQueueFamilyCheckpointProperties2NV* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCheckpointData2NV(VkStructureType rootType,
                                           VkCheckpointData2NV* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_zero_initialize_workgroup_memory

#endif
#ifdef VK_KHR_copy_commands2

#endif
#ifdef VK_KHR_format_feature_flags2

#endif
#ifdef VK_KHR_maintenance4

#endif
#ifdef VK_KHR_maintenance5
void decode_from_stream_VkPhysicalDeviceMaintenance5FeaturesKHR(
    VkStructureType rootType,
    VkPhysicalDeviceMaintenance5FeaturesKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceMaintenance5PropertiesKHR(
    VkStructureType rootType,
    VkPhysicalDeviceMaintenance5PropertiesKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderingAreaInfoKHR(VkStructureType rootType,
                                              VkRenderingAreaInfoKHR* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkImageSubresource2KHR(VkStructureType rootType,
                                              VkImageSubresource2KHR* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkDeviceImageSubresourceInfoKHR(
    VkStructureType rootType,
    VkDeviceImageSubresourceInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubresourceLayout2KHR(VkStructureType rootType,
                                               VkSubresourceLayout2KHR* forUnmarshaling,
                                               uint8_t** ptr);

void decode_from_stream_VkPipelineCreateFlags2CreateInfoKHR(
    VkStructureType rootType,
    VkPipelineCreateFlags2CreateInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkBufferUsageFlags2CreateInfoKHR(
    VkStructureType rootType,
    VkBufferUsageFlags2CreateInfoKHR* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_ANDROID_native_buffer
void decode_from_stream_VkNativeBufferUsage2ANDROID(VkStructureType rootType,
                                                   VkNativeBufferUsage2ANDROID* forUnmarshaling,
                                                   uint8_t** ptr);

void decode_from_stream_VkNativeBufferANDROID(VkStructureType rootType,
                                             VkNativeBufferANDROID* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSwapchainImageCreateInfoANDROID(
    VkStructureType rootType,
    VkSwapchainImageCreateInfoANDROID* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDevicePresentationPropertiesANDROID(
    VkStructureType rootType,
    VkPhysicalDevicePresentationPropertiesANDROID* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_debug_report
void decode_from_stream_VkDebugReportCallbackCreateInfoEXT(
    VkStructureType rootType,
    VkDebugReportCallbackCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_transform_feedback
void decode_from_stream_VkPhysicalDeviceTransformFeedbackFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceTransformFeedbackFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceTransformFeedbackPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceTransformFeedbackPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineRasterizationStateStreamCreateInfoEXT(
    VkStructureType rootType,
    VkPipelineRasterizationStateStreamCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_texture_compression_astc_hdr

#endif
#ifdef VK_EXT_depth_clip_enable
void decode_from_stream_VkPhysicalDeviceDepthClipEnableFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceDepthClipEnableFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineRasterizationDepthClipStateCreateInfoEXT(
    VkStructureType rootType,
    VkPipelineRasterizationDepthClipStateCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_debug_utils
void decode_from_stream_VkDebugUtilsLabelEXT(VkStructureType rootType,
                                            VkDebugUtilsLabelEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDebugUtilsObjectNameInfoEXT(VkStructureType rootType,
                                                     VkDebugUtilsObjectNameInfoEXT* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkDebugUtilsMessengerCallbackDataEXT(
    VkStructureType rootType,
    VkDebugUtilsMessengerCallbackDataEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDebugUtilsMessengerCreateInfoEXT(
    VkStructureType rootType,
    VkDebugUtilsMessengerCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDebugUtilsObjectTagInfoEXT(VkStructureType rootType,
                                                    VkDebugUtilsObjectTagInfoEXT* forUnmarshaling,
                                                    uint8_t** ptr);

#endif
#ifdef VK_EXT_inline_uniform_block

#endif
#ifdef VK_EXT_image_drm_format_modifier
void decode_from_stream_VkDrmFormatModifierPropertiesEXT(
    VkStructureType rootType,
    VkDrmFormatModifierPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDrmFormatModifierPropertiesListEXT(
    VkStructureType rootType,
    VkDrmFormatModifierPropertiesListEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceImageDrmFormatModifierInfoEXT(
    VkStructureType rootType,
    VkPhysicalDeviceImageDrmFormatModifierInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageDrmFormatModifierListCreateInfoEXT(
    VkStructureType rootType,
    VkImageDrmFormatModifierListCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageDrmFormatModifierExplicitCreateInfoEXT(
    VkStructureType rootType,
    VkImageDrmFormatModifierExplicitCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageDrmFormatModifierPropertiesEXT(
    VkStructureType rootType,
    VkImageDrmFormatModifierPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDrmFormatModifierProperties2EXT(
    VkStructureType rootType,
    VkDrmFormatModifierProperties2EXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDrmFormatModifierPropertiesList2EXT(
    VkStructureType rootType,
    VkDrmFormatModifierPropertiesList2EXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_external_memory_host
void decode_from_stream_VkImportMemoryHostPointerInfoEXT(
    VkStructureType rootType,
    VkImportMemoryHostPointerInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryHostPointerPropertiesEXT(
    VkStructureType rootType,
    VkMemoryHostPointerPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceExternalMemoryHostPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceExternalMemoryHostPropertiesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_vertex_attribute_divisor
void decode_from_stream_VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkVertexInputBindingDivisorDescriptionEXT(
    VkStructureType rootType,
    VkVertexInputBindingDivisorDescriptionEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineVertexInputDivisorStateCreateInfoEXT(
    VkStructureType rootType,
    VkPipelineVertexInputDivisorStateCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_pipeline_creation_feedback

#endif
#ifdef VK_EXT_fragment_density_map
void decode_from_stream_VkPhysicalDeviceFragmentDensityMapFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceFragmentDensityMapFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceFragmentDensityMapPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceFragmentDensityMapPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRenderPassFragmentDensityMapCreateInfoEXT(
    VkStructureType rootType,
    VkRenderPassFragmentDensityMapCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_scalar_block_layout

#endif
#ifdef VK_EXT_subgroup_size_control

#endif
#ifdef VK_EXT_tooling_info

#endif
#ifdef VK_EXT_validation_features
void decode_from_stream_VkValidationFeaturesEXT(VkStructureType rootType,
                                               VkValidationFeaturesEXT* forUnmarshaling,
                                               uint8_t** ptr);

#endif
#ifdef VK_EXT_provoking_vertex
void decode_from_stream_VkPhysicalDeviceProvokingVertexFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceProvokingVertexFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceProvokingVertexPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceProvokingVertexPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineRasterizationProvokingVertexStateCreateInfoEXT(
    VkStructureType rootType,
    VkPipelineRasterizationProvokingVertexStateCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_line_rasterization
void decode_from_stream_VkPhysicalDeviceLineRasterizationFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceLineRasterizationFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceLineRasterizationPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceLineRasterizationPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineRasterizationLineStateCreateInfoEXT(
    VkStructureType rootType,
    VkPipelineRasterizationLineStateCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_index_type_uint8
void decode_from_stream_VkPhysicalDeviceIndexTypeUint8FeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceIndexTypeUint8FeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_extended_dynamic_state
void decode_from_stream_VkPhysicalDeviceExtendedDynamicStateFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceExtendedDynamicStateFeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_host_image_copy
void decode_from_stream_VkPhysicalDeviceHostImageCopyFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceHostImageCopyFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceHostImageCopyPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceHostImageCopyPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkMemoryToImageCopyEXT(VkStructureType rootType,
                                              VkMemoryToImageCopyEXT* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkImageToMemoryCopyEXT(VkStructureType rootType,
                                              VkImageToMemoryCopyEXT* forUnmarshaling,
                                              uint8_t** ptr);

void decode_from_stream_VkCopyMemoryToImageInfoEXT(VkStructureType rootType,
                                                  VkCopyMemoryToImageInfoEXT* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkCopyImageToMemoryInfoEXT(VkStructureType rootType,
                                                  VkCopyImageToMemoryInfoEXT* forUnmarshaling,
                                                  uint8_t** ptr);

void decode_from_stream_VkCopyImageToImageInfoEXT(VkStructureType rootType,
                                                 VkCopyImageToImageInfoEXT* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkHostImageLayoutTransitionInfoEXT(
    VkStructureType rootType,
    VkHostImageLayoutTransitionInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSubresourceHostMemcpySizeEXT(
    VkStructureType rootType,
    VkSubresourceHostMemcpySizeEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkHostImageCopyDevicePerformanceQueryEXT(
    VkStructureType rootType,
    VkHostImageCopyDevicePerformanceQueryEXT* forUnmarshaling, uint8_t** ptr);


#endif
#ifdef VK_EXT_swapchain_maintenance1
void decode_from_stream_VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSwapchainPresentFenceInfoEXT(
    VkStructureType rootType,
    VkSwapchainPresentFenceInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSwapchainPresentModesCreateInfoEXT(
    VkStructureType rootType,
    VkSwapchainPresentModesCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkSwapchainPresentModeInfoEXT(VkStructureType rootType,
                                                     VkSwapchainPresentModeInfoEXT* forUnmarshaling,
                                                     uint8_t** ptr);

void decode_from_stream_VkSwapchainPresentScalingCreateInfoEXT(
    VkStructureType rootType,
    VkSwapchainPresentScalingCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkReleaseSwapchainImagesInfoEXT(
    VkStructureType rootType,
    VkReleaseSwapchainImagesInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_shader_demote_to_helper_invocation

#endif
#ifdef VK_EXT_texel_buffer_alignment
void decode_from_stream_VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT* forUnmarshaling, uint8_t** ptr);


#endif
#ifdef VK_EXT_device_memory_report
void decode_from_stream_VkPhysicalDeviceDeviceMemoryReportFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceDeviceMemoryReportFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceMemoryReportCallbackDataEXT(
    VkStructureType rootType,
    VkDeviceMemoryReportCallbackDataEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkDeviceDeviceMemoryReportCreateInfoEXT(
    VkStructureType rootType,
    VkDeviceDeviceMemoryReportCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_robustness2
void decode_from_stream_VkPhysicalDeviceRobustness2FeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceRobustness2FeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceRobustness2PropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceRobustness2PropertiesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_custom_border_color
void decode_from_stream_VkSamplerCustomBorderColorCreateInfoEXT(
    VkStructureType rootType,
    VkSamplerCustomBorderColorCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceCustomBorderColorPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceCustomBorderColorPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceCustomBorderColorFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceCustomBorderColorFeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_private_data

#endif
#ifdef VK_EXT_pipeline_creation_cache_control

#endif
#ifdef VK_EXT_graphics_pipeline_library
void decode_from_stream_VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkGraphicsPipelineLibraryCreateInfoEXT(
    VkStructureType rootType,
    VkGraphicsPipelineLibraryCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_ycbcr_2plane_444_formats
void decode_from_stream_VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_image_robustness

#endif
#ifdef VK_EXT_image_compression_control
void decode_from_stream_VkPhysicalDeviceImageCompressionControlFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceImageCompressionControlFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkImageCompressionControlEXT(VkStructureType rootType,
                                                    VkImageCompressionControlEXT* forUnmarshaling,
                                                    uint8_t** ptr);

void decode_from_stream_VkImageCompressionPropertiesEXT(
    VkStructureType rootType,
    VkImageCompressionPropertiesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_4444_formats
void decode_from_stream_VkPhysicalDevice4444FormatsFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDevice4444FormatsFeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_primitive_topology_list_restart
void decode_from_stream_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_extended_dynamic_state2
void decode_from_stream_VkPhysicalDeviceExtendedDynamicState2FeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceExtendedDynamicState2FeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_color_write_enable
void decode_from_stream_VkPhysicalDeviceColorWriteEnableFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceColorWriteEnableFeaturesEXT* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPipelineColorWriteCreateInfoEXT(
    VkStructureType rootType,
    VkPipelineColorWriteCreateInfoEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_GOOGLE_gfxstream
void decode_from_stream_VkImportColorBufferGOOGLE(VkStructureType rootType,
                                                 VkImportColorBufferGOOGLE* forUnmarshaling,
                                                 uint8_t** ptr);

void decode_from_stream_VkImportBufferGOOGLE(VkStructureType rootType,
                                            VkImportBufferGOOGLE* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkCreateBlobGOOGLE(VkStructureType rootType,
                                          VkCreateBlobGOOGLE* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_image_compression_control_swapchain
void decode_from_stream_VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT(
    VkStructureType rootType,
    VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT* forUnmarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_ray_tracing_pipeline
void decode_from_stream_VkRayTracingShaderGroupCreateInfoKHR(
    VkStructureType rootType,
    VkRayTracingShaderGroupCreateInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRayTracingPipelineInterfaceCreateInfoKHR(
    VkStructureType rootType,
    VkRayTracingPipelineInterfaceCreateInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkRayTracingPipelineCreateInfoKHR(
    VkStructureType rootType,
    VkRayTracingPipelineCreateInfoKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceRayTracingPipelineFeaturesKHR(
    VkStructureType rootType,
    VkPhysicalDeviceRayTracingPipelineFeaturesKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkPhysicalDeviceRayTracingPipelinePropertiesKHR(
    VkStructureType rootType,
    VkPhysicalDeviceRayTracingPipelinePropertiesKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkStridedDeviceAddressRegionKHR(
    VkStructureType rootType,
    VkStridedDeviceAddressRegionKHR* forUnmarshaling, uint8_t** ptr);

void decode_from_stream_VkTraceRaysIndirectCommandKHR(VkStructureType rootType,
                                                     VkTraceRaysIndirectCommandKHR* forUnmarshaling,
                                                     uint8_t** ptr);

#endif