#include <vulkan/vulkan.h>

#include "hw/vsoc/express_platform.h"
#include "hw/vsoc/gpu/express_gpu.h"

#define FUNID_vkCreateInstance 1000
// #define FUNID_vkDestroyInstance 1001
// #define FUNID_vkEnumeratePhysicalDevices 1002
// #define FUNID_vkGetPhysicalDeviceFeatures 1003
// #define FUNID_vkGetPhysicalDeviceFormatProperties 1004
// #define FUNID_vkGetPhysicalDeviceImageFormatProperties 1005
// #define FUNID_vkGetPhysicalDeviceProperties 1006
// #define FUNID_vkGetPhysicalDeviceQueueFamilyProperties 1007
// #define FUNID_vkGetPhysicalDeviceMemoryProperties 1008
// #define FUNID_vkGetInstanceProcAddr 1009
// #define FUNID_vkGetDeviceProcAddr 1010
#define FUNID_vkAcquireNextImage2KHR 1011
#define FUNID_vkAcquireNextImageKHR 1012
#define FUNID_vkAllocateCommandBuffers 1013
#define FUNID_vkAllocateDescriptorSets 1014
#define FUNID_vkAllocateMemory 1015
#define FUNID_vkBeginCommandBuffer 1016
#define FUNID_vkBindBufferMemory 1017
#define FUNID_vkBindBufferMemory2 1018
#define FUNID_vkBindImageMemory 1019
#define FUNID_vkBindImageMemory2 1020
#define FUNID_vkCmdBeginQuery 1021
#define FUNID_vkCmdBeginRendering 1022
#define FUNID_vkCmdBeginRenderPass 1023
#define FUNID_vkCmdBeginRenderPass2 1024
#define FUNID_vkCmdBindDescriptorSets 1025
#define FUNID_vkCmdBindIndexBuffer 1026
#define FUNID_vkCmdBindPipeline 1027
#define FUNID_vkCmdBindVertexBuffers 1028
#define FUNID_vkCmdBindVertexBuffers2 1029
#define FUNID_vkCmdBlitImage 1030
#define FUNID_vkCmdBlitImage2 1031
#define FUNID_vkCmdClearAttachments 1032
#define FUNID_vkCmdClearColorImage 1033
#define FUNID_vkCmdClearDepthStencilImage 1034
#define FUNID_vkCmdCopyBuffer 1035
#define FUNID_vkCmdCopyBuffer2 1036
#define FUNID_vkCmdCopyBufferToImage 1037
#define FUNID_vkCmdCopyBufferToImage2 1038
#define FUNID_vkCmdCopyImage 1039
#define FUNID_vkCmdCopyImage2 1040
#define FUNID_vkCmdCopyImageToBuffer 1041
#define FUNID_vkCmdCopyImageToBuffer2 1042
#define FUNID_vkCmdCopyQueryPoolResults 1043
#define FUNID_vkCmdDispatch 1044
#define FUNID_vkCmdDispatchBase 1045
#define FUNID_vkCmdDispatchIndirect 1046
#define FUNID_vkCmdDraw 1047
#define FUNID_vkCmdDrawIndexed 1048
#define FUNID_vkCmdDrawIndexedIndirect 1049
#define FUNID_vkCmdDrawIndexedIndirectCount 1050
#define FUNID_vkCmdDrawIndirect 1051
#define FUNID_vkCmdDrawIndirectCount 1052
#define FUNID_vkCmdEndQuery 1053
#define FUNID_vkCmdEndRendering 1054
#define FUNID_vkCmdEndRenderPass 1055
#define FUNID_vkCmdEndRenderPass2 1056
#define FUNID_vkCmdExecuteCommands 1057
#define FUNID_vkCmdFillBuffer 1058
#define FUNID_vkCmdNextSubpass 1059
#define FUNID_vkCmdNextSubpass2 1060
#define FUNID_vkCmdPipelineBarrier 1061
#define FUNID_vkCmdPipelineBarrier2 1062
#define FUNID_vkCmdPushConstants 1063
#define FUNID_vkCmdResetEvent 1064
#define FUNID_vkCmdResetEvent2 1065
#define FUNID_vkCmdResetQueryPool 1066
#define FUNID_vkCmdResolveImage 1067
#define FUNID_vkCmdResolveImage2 1068
#define FUNID_vkCmdSetBlendConstants 1069
#define FUNID_vkCmdSetCullMode 1070
#define FUNID_vkCmdSetDepthBias 1071
#define FUNID_vkCmdSetDepthBiasEnable 1072
#define FUNID_vkCmdSetDepthBounds 1073
#define FUNID_vkCmdSetDepthBoundsTestEnable 1074
#define FUNID_vkCmdSetDepthCompareOp 1075
#define FUNID_vkCmdSetDepthTestEnable 1076
#define FUNID_vkCmdSetDepthWriteEnable 1077
#define FUNID_vkCmdSetDeviceMask 1078
#define FUNID_vkCmdSetEvent 1079
#define FUNID_vkCmdSetEvent2 1080
#define FUNID_vkCmdSetFrontFace 1081
#define FUNID_vkCmdSetLineWidth 1082
#define FUNID_vkCmdSetPrimitiveRestartEnable 1083
#define FUNID_vkCmdSetPrimitiveTopology 1084
#define FUNID_vkCmdSetRasterizerDiscardEnable 1085
#define FUNID_vkCmdSetScissor 1086
#define FUNID_vkCmdSetScissorWithCount 1087
#define FUNID_vkCmdSetStencilCompareMask 1088
#define FUNID_vkCmdSetStencilOp 1089
#define FUNID_vkCmdSetStencilReference 1090
#define FUNID_vkCmdSetStencilTestEnable 1091
#define FUNID_vkCmdSetStencilWriteMask 1092
#define FUNID_vkCmdSetViewport 1093
#define FUNID_vkCmdSetViewportWithCount 1094
#define FUNID_vkCmdUpdateBuffer 1095
#define FUNID_vkCmdWaitEvents 1096
#define FUNID_vkCmdWaitEvents2 1097
#define FUNID_vkCmdWriteTimestamp 1098
#define FUNID_vkCmdWriteTimestamp2 1099
#define FUNID_vkCreateBuffer                              1100
#define FUNID_vkCreateBufferView                          1101
#define FUNID_vkCreateCommandPool                         1102
#define FUNID_vkCreateComputePipelines                    1103
#define FUNID_vkCreateDescriptorPool                      1104
#define FUNID_vkCreateDescriptorSetLayout                 1105
#define FUNID_vkCreateDescriptorUpdateTemplate            1106
#define FUNID_vkCreateDevice                              1107
#define FUNID_vkCreateDisplayModeKHR                      1108
#define FUNID_vkCreateDisplayPlaneSurfaceKHR              1109
#define FUNID_vkCreateEvent                               1110
#define FUNID_vkCreateFence                               1111
#define FUNID_vkCreateFramebuffer                         1112
#define FUNID_vkCreateGraphicsPipelines                   1113
#define FUNID_vkCreateImage                               1114
#define FUNID_vkCreateImageView                           1115
#define FUNID_vkCreatePipelineCache                       1116
#define FUNID_vkCreatePipelineLayout                      1117
#define FUNID_vkCreatePrivateDataSlot                     1118
#define FUNID_vkCreateQueryPool                           1119
#define FUNID_vkCreateRenderPass                          1120
#define FUNID_vkCreateRenderPass2                         1121
#define FUNID_vkCreateSampler                             1122
#define FUNID_vkCreateSamplerYcbcrConversion              1123
#define FUNID_vkCreateSemaphore                           1124
#define FUNID_vkCreateShaderModule                        1125
#define FUNID_vkCreateSharedSwapchainsKHR                 1126
#define FUNID_vkCreateSwapchainKHR                        1127
#define FUNID_vkDestroyBuffer                             1128
#define FUNID_vkDestroyBufferView                         1129
#define FUNID_vkDestroyCommandPool                        1130
#define FUNID_vkDestroyDescriptorPool                     1131
#define FUNID_vkDestroyDescriptorSetLayout                1132
#define FUNID_vkDestroyDescriptorUpdateTemplate           1133
#define FUNID_vkDestroyDevice                             1134
#define FUNID_vkDestroyEvent                              1135
#define FUNID_vkDestroyFence                              1136
#define FUNID_vkDestroyFramebuffer                        1137
#define FUNID_vkDestroyImage                              1138
#define FUNID_vkDestroyImageView                          1139
#define FUNID_vkDestroyInstance                           1140
#define FUNID_vkDestroyPipeline                           1141
#define FUNID_vkDestroyPipelineCache                      1142
#define FUNID_vkDestroyPipelineLayout                     1143
#define FUNID_vkDestroyPrivateDataSlot                    1144
#define FUNID_vkDestroyQueryPool                          1145
#define FUNID_vkDestroyRenderPass                         1146
#define FUNID_vkDestroySampler                            1147
#define FUNID_vkDestroySamplerYcbcrConversion             1148
#define FUNID_vkDestroySemaphore                          1149
#define FUNID_vkDestroyShaderModule                       1150
#define FUNID_vkDestroySurfaceKHR                         1151
#define FUNID_vkDestroySwapchainKHR                       1152
#define FUNID_vkDeviceWaitIdle                            1153
#define FUNID_vkEndCommandBuffer                          1154
#define FUNID_vkEnumerateDeviceExtensionProperties        1155
#define FUNID_vkEnumerateDeviceLayerProperties            1156
#define FUNID_vkEnumerateInstanceExtensionProperties      1157
#define FUNID_vkEnumerateInstanceLayerProperties          1158
#define FUNID_vkEnumerateInstanceVersion                  1159
#define FUNID_vkEnumeratePhysicalDeviceGroups             1160
#define FUNID_vkEnumeratePhysicalDevices                  1161
#define FUNID_vkFlushMappedMemoryRanges                   1162
#define FUNID_vkFreeCommandBuffers                        1163
#define FUNID_vkFreeDescriptorSets                        1164
#define FUNID_vkFreeMemory                                1165
#define FUNID_vkGetBufferDeviceAddress                    1166
#define FUNID_vkGetBufferMemoryRequirements               1167
#define FUNID_vkGetBufferMemoryRequirements2              1168
#define FUNID_vkGetBufferOpaqueCaptureAddress             1169
#define FUNID_vkGetDescriptorSetLayoutSupport             1170
#define FUNID_vkGetDeviceBufferMemoryRequirements         1171
#define FUNID_vkGetDeviceGroupPeerMemoryFeatures          1172
#define FUNID_vkGetDeviceGroupPresentCapabilitiesKHR      1173
#define FUNID_vkGetDeviceGroupSurfacePresentModesKHR      1174
#define FUNID_vkGetDeviceImageMemoryRequirements          1175
#define FUNID_vkGetDeviceImageSparseMemoryRequirements    1176
#define FUNID_vkGetDeviceMemoryCommitment                 1177
#define FUNID_vkGetDeviceMemoryOpaqueCaptureAddress       1178
#define FUNID_vkGetDeviceProcAddr                         1179
#define FUNID_vkGetDeviceQueue                            1180
#define FUNID_vkGetDeviceQueue2                           1181
#define FUNID_vkGetDisplayModeProperties2KHR              1182
#define FUNID_vkGetDisplayModePropertiesKHR               1183
#define FUNID_vkGetDisplayPlaneCapabilities2KHR           1184
#define FUNID_vkGetDisplayPlaneCapabilitiesKHR            1185
#define FUNID_vkGetDisplayPlaneSupportedDisplaysKHR       1186
#define FUNID_vkGetEventStatus                            1187
#define FUNID_vkGetFenceStatus                            1188
#define FUNID_vkGetImageMemoryRequirements                1189
#define FUNID_vkGetImageMemoryRequirements2               1190
#define FUNID_vkGetImageSparseMemoryRequirements          1191
#define FUNID_vkGetImageSparseMemoryRequirements2         1192
#define FUNID_vkGetImageSubresourceLayout                 1193
#define FUNID_vkGetInstanceProcAddr                       1194
#define FUNID_vkGetPhysicalDeviceDisplayPlaneProperties2KHR 1195
#define FUNID_vkGetPhysicalDeviceDisplayPlanePropertiesKHR 1196
#define FUNID_vkGetPhysicalDeviceDisplayProperties2KHR     1197
#define FUNID_vkGetPhysicalDeviceDisplayPropertiesKHR      1198
#define FUNID_vkGetPhysicalDeviceExternalBufferProperties  1199
#define FUNID_vkGetPhysicalDeviceExternalFenceProperties   1200
#define FUNID_vkGetPhysicalDeviceExternalSemaphoreProperties 1201
#define FUNID_vkGetPhysicalDeviceFeatures                  1202
#define FUNID_vkGetPhysicalDeviceFeatures2                 1203
#define FUNID_vkGetPhysicalDeviceFormatProperties          1204
#define FUNID_vkGetPhysicalDeviceFormatProperties2         1205
#define FUNID_vkGetPhysicalDeviceImageFormatProperties     1206
#define FUNID_vkGetPhysicalDeviceImageFormatProperties2    1207
#define FUNID_vkGetPhysicalDeviceMemoryProperties          1208
#define FUNID_vkGetPhysicalDeviceMemoryProperties2         1209
#define FUNID_vkGetPhysicalDevicePresentRectanglesKHR      1210
#define FUNID_vkGetPhysicalDeviceProperties                1211
#define FUNID_vkGetPhysicalDeviceProperties2               1212
#define FUNID_vkGetPhysicalDeviceQueueFamilyProperties     1213
#define FUNID_vkGetPhysicalDeviceQueueFamilyProperties2    1214
#define FUNID_vkGetPhysicalDeviceSparseImageFormatProperties 1215
#define FUNID_vkGetPhysicalDeviceSparseImageFormatProperties2 1216
#define FUNID_vkGetPhysicalDeviceSurfaceCapabilities2KHR   1217
#define FUNID_vkGetPhysicalDeviceSurfaceCapabilitiesKHR    1218
#define FUNID_vkGetPhysicalDeviceSurfaceFormats2KHR        1219
#define FUNID_vkGetPhysicalDeviceSurfaceFormatsKHR         1220
#define FUNID_vkGetPhysicalDeviceSurfacePresentModesKHR    1221
#define FUNID_vkGetPhysicalDeviceSurfaceSupportKHR         1222
#define FUNID_vkGetPhysicalDeviceToolProperties            1223
#define FUNID_vkGetPipelineCacheData                       1224
#define FUNID_vkGetPrivateData                             1225
#define FUNID_vkGetQueryPoolResults                        1226
#define FUNID_vkGetRenderAreaGranularity                   1227
#define FUNID_vkGetSemaphoreCounterValue                   1228
#define FUNID_vkGetSwapchainImagesKHR                      1229
#define FUNID_vkInvalidateMappedMemoryRanges               1230
#define FUNID_vkMapMemory                                  1231
#define FUNID_vkMergePipelineCaches                        1232
#define FUNID_vkQueueBindSparse                            1233
#define FUNID_vkQueuePresentKHR                            1234
#define FUNID_vkQueueSubmit                                1235
#define FUNID_vkQueueSubmit2                               1236
#define FUNID_vkQueueWaitIdle                              1237
#define FUNID_vkResetCommandBuffer                         1238
#define FUNID_vkResetCommandPool                           1239
#define FUNID_vkResetDescriptorPool                        1240
#define FUNID_vkResetEvent                                 1241
#define FUNID_vkResetFences                                1242
#define FUNID_vkResetQueryPool                             1243
#define FUNID_vkSetEvent                                   1244
#define FUNID_vkSetPrivateData                             1245
#define FUNID_vkSignalSemaphore                            1246
#define FUNID_vkTrimCommandPool                            1247
#define FUNID_vkUnmapMemory                                1248
#define FUNID_vkUpdateDescriptorSets                       1249
#define FUNID_vkUpdateDescriptorSetWithTemplate            1250
#define FUNID_vkWaitForFences                              1251
#define FUNID_vkWaitSemaphores                             1252
#define FUNID_vkCreateAndroidSurfaceKHR                    1253

#define FUNID_vkCreateSurfaceOHOS                          1254
#define FUNID_vkGetNativeBufferPropertiesOHOS              1255
#define FUNID_vkGetMemoryNativeBufferOHOS                  1256


void vk_decode_invoke(Render_Thread_Context *context, Teleport_Express_Call *call);