

//#ifndef DEFINE_H
//#define DEFINE_H

#ifndef GLV3_TRANS_H
#define GLV3_TRANS_H

#include "direct-express/direct_express_distribute.h"
#include "direct-express/express_device_common.h"
#include "express-gpu/offscreen_render_thread.h"


//android
// #include <GLES/glplatform.h>
// #include <GLES/gl.h>
// #include <GLES2/gl2.h>
// #include <GLES2/gl2platform.h>
// #include <GLES2/gl2ext.h>
// #include <GLES3/gl3.h>


//# define EXPRESS_GPU_FUN_ID ((unsigned long long)1)


#define MAX_OUT_BUF_LEN 4000


#define FUNID_glMapBufferRange_read ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+1)
#define FUNID_glCheckFramebufferStatus ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+2)
#define FUNID_glCreateProgram ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+3)
#define FUNID_glCreateShader ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+4)
#define FUNID_glGetError ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+5)
#define FUNID_glIsBuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+6)
#define FUNID_glIsEnabled ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+7)
#define FUNID_glIsFramebuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+8)
#define FUNID_glIsProgram ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+9)
#define FUNID_glIsRenderbuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+10)
#define FUNID_glIsShader ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+11)
#define FUNID_glIsTexture ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+12)
#define FUNID_glIsQuery ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+13)
#define FUNID_glIsVertexArray ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+14)
#define FUNID_glIsSampler ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+15)
#define FUNID_glIsTransformFeedback ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+16)
#define FUNID_glGetAttribLocation ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+17)
#define FUNID_glGetUniformLocation ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+18)
#define FUNID_glGetFragDataLocation ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+19)
#define FUNID_glGetUniformBlockIndex ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+20)
#define FUNID_glGetProgramResourceIndex ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+21)
#define FUNID_glGetProgramResourceLocation ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+22)
#define FUNID_glCreateShaderProgramv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+23)
#define FUNID_glQueryMatrixxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+24)
#define FUNID_glGenBuffers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+25)
#define FUNID_glGenFramebuffers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+26)
#define FUNID_glGenRenderbuffers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+27)
#define FUNID_glGenTextures ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+28)
#define FUNID_glGetActiveAttrib ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+29)
#define FUNID_glGetActiveUniform ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+30)
#define FUNID_glGetAttachedShaders ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+31)
#define FUNID_glGetBooleanv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+32)
#define FUNID_glGetBufferParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+33)
#define FUNID_glGetFloatv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+34)
#define FUNID_glGetFramebufferAttachmentParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+35)
#define FUNID_glGetIntegerv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+36)
#define FUNID_glGetProgramiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+37)
#define FUNID_glGetProgramInfoLog ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+38)
#define FUNID_glGetRenderbufferParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+39)
#define FUNID_glGetShaderiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+40)
#define FUNID_glGetShaderInfoLog ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+41)
#define FUNID_glGetShaderPrecisionFormat ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+42)
#define FUNID_glGetShaderSource ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+43)
#define FUNID_glGetTexParameterfv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+44)
#define FUNID_glGetTexParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+45)
#define FUNID_glGetUniformfv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+46)
#define FUNID_glGetUniformiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+47)
#define FUNID_glGetUniformuiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+48)
#define FUNID_glGetUniformIndices ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+49)
#define FUNID_glGetVertexAttribfv_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+50)
#define FUNID_glGetVertexAttribiv_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+51)
#define FUNID_glReadPixels_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+52)
#define FUNID_glReadPixels_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+53)
#define FUNID_glGenQueries ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+54)
#define FUNID_glGetQueryiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+55)
#define FUNID_glGetQueryObjectuiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+56)
#define FUNID_glGenVertexArrays_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+57)
#define FUNID_glGetIntegeri_v ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+58)
#define FUNID_glGetTransformFeedbackVarying ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+59)
#define FUNID_glGetVertexAttribIiv_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+60)
#define FUNID_glGetVertexAttribIuiv_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+61)
#define FUNID_glGetActiveUniformsiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+62)
#define FUNID_glGetActiveUniformBlockiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+63)
#define FUNID_glGetActiveUniformBlockName ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+64)
#define FUNID_glGetInteger64v ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+65)
#define FUNID_glGetInteger64i_v ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+66)
#define FUNID_glGetBufferParameteri64v ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+67)
#define FUNID_glGenSamplers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+68)
#define FUNID_glGetSamplerParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+69)
#define FUNID_glGetSamplerParameterfv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+70)
#define FUNID_glGenTransformFeedbacks ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+71)
#define FUNID_glGetProgramBinary ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+72)
#define FUNID_glGetInternalformativ ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+73)
#define FUNID_glGetClipPlanexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+74)
#define FUNID_glGetFixedvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+75)
#define FUNID_glGetTexEnvxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+76)
#define FUNID_glGetTexParameterxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+77)
#define FUNID_glGetLightxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+78)
#define FUNID_glGetMaterialxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+79)
#define FUNID_glGetTexGenxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+80)
#define FUNID_glShaderSource ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+81)
#define FUNID_glTransformFeedbackVaryings ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+82)
#define FUNID_glGetFramebufferParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+83)
#define FUNID_glGetProgramInterfaceiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+84)
#define FUNID_glGetProgramResourceName ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+85)
#define FUNID_glGetProgramResourceiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+86)
#define FUNID_glGenProgramPipelines ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+87)
#define FUNID_glGetProgramPipelineiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+88)
#define FUNID_glGetProgramPipelineInfoLog ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+89)
#define FUNID_glGetBooleani_v ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+90)
#define FUNID_glGetMultisamplefv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+91)
#define FUNID_glGetTexLevelParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+92)
#define FUNID_glGetTexLevelParameterfv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+93)
#define FUNID_glFenceSync ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+94)
#define FUNID_glIsSync ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+95)
#define FUNID_glGetSynciv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+96)
#define FUNID_glClientWaitSync ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+97)
#define FUNID_glFinish ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+98)
#define FUNID_glUnmapBuffer_special ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+99)
#define FUNID_glBindAttribLocation ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+100)
#define FUNID_glBufferData_custom ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+101)
#define FUNID_glBufferSubData_custom ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+102)
#define FUNID_glCompressedTexImage2D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+103)
#define FUNID_glCompressedTexSubImage2D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+104)
#define FUNID_glDrawElements_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+105)
#define FUNID_glTexImage2D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+106)
#define FUNID_glDrawRangeElements_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+107)
#define FUNID_glCompressedTexImage3D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+108)
#define FUNID_glCompressedTexSubImage3D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+109)
#define FUNID_glTexSubImage2D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+110)
#define FUNID_glTexImage3D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+111)
#define FUNID_glTexSubImage3D_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+112)
#define FUNID_glDrawElementsInstanced_without_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+113)
#define FUNID_glTestInt1 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+114)
#define FUNID_glTestInt2 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+115)
#define FUNID_glTestInt3 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+116)
#define FUNID_glTestInt4 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+117)
#define FUNID_glTestInt5 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+118)
#define FUNID_glTestInt6 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+119)
#define FUNID_glTestPointer1 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+120)
#define FUNID_glTestPointer2 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+121)
#define FUNID_glTestPointer3 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+122)
#define FUNID_glTestPointer4 ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0x8+0x4)<<24u)+123)
#define FUNID_glTestString ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+124)
#define FUNID_glPrintf ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+125)
#define FUNID_glInOutTest ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x4)<<24u)+126)
#define FUNID_glActiveTexture ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+127)
#define FUNID_glAttachShader ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+128)
#define FUNID_glBindBuffer_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+129)
#define FUNID_glBindFramebuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+130)
#define FUNID_glBindRenderbuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+131)
#define FUNID_glBindTexture ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+132)
#define FUNID_glBlendColor ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+133)
#define FUNID_glBlendEquation ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+134)
#define FUNID_glBlendEquationSeparate ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+135)
#define FUNID_glBlendFunc ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+136)
#define FUNID_glBlendFuncSeparate ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+137)
#define FUNID_glClear ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+138)
#define FUNID_glClearColor ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+139)
#define FUNID_glClearDepthf ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+140)
#define FUNID_glClearStencil ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+141)
#define FUNID_glColorMask ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+142)
#define FUNID_glCompileShader ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+143)
#define FUNID_glCopyTexImage2D ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+144)
#define FUNID_glCopyTexSubImage2D ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+145)
#define FUNID_glCullFace ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+146)
#define FUNID_glDeleteProgram_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+147)
#define FUNID_glDeleteShader ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+148)
#define FUNID_glDepthFunc ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+149)
#define FUNID_glDepthMask ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+150)
#define FUNID_glDepthRangef ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+151)
#define FUNID_glDetachShader ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+152)
#define FUNID_glDisable ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+153)
#define FUNID_glDisableVertexAttribArray_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+154)
#define FUNID_glDrawArrays_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+155)
#define FUNID_glEnable ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+156)
#define FUNID_glEnableVertexAttribArray_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+157)
#define FUNID_glFlush ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+158)
#define FUNID_glFramebufferRenderbuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+159)
#define FUNID_glFramebufferTexture2D ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+160)
#define FUNID_glFrontFace ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+161)
#define FUNID_glGenerateMipmap ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+162)
#define FUNID_glHint ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+163)
#define FUNID_glLineWidth ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+164)
#define FUNID_glLinkProgram_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+165)
#define FUNID_glPixelStorei_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+166)
#define FUNID_glPolygonOffset ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+167)
#define FUNID_glReleaseShaderCompiler ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+168)
#define FUNID_glRenderbufferStorage ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+169)
#define FUNID_glSampleCoverage ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+170)
#define FUNID_glScissor ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+171)
#define FUNID_glStencilFunc ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+172)
#define FUNID_glStencilFuncSeparate ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+173)
#define FUNID_glStencilMask ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+174)
#define FUNID_glStencilMaskSeparate ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+175)
#define FUNID_glStencilOp ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+176)
#define FUNID_glStencilOpSeparate ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+177)
#define FUNID_glTexParameterf ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+178)
#define FUNID_glTexParameteri ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+179)
#define FUNID_glUniform1f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+180)
#define FUNID_glUniform1i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+181)
#define FUNID_glUniform2f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+182)
#define FUNID_glUniform2i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+183)
#define FUNID_glUniform3f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+184)
#define FUNID_glUniform3i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+185)
#define FUNID_glUniform4f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+186)
#define FUNID_glUniform4i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+187)
#define FUNID_glUseProgram ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+188)
#define FUNID_glValidateProgram ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+189)
#define FUNID_glVertexAttrib1f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+190)
#define FUNID_glVertexAttrib2f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+191)
#define FUNID_glVertexAttrib3f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+192)
#define FUNID_glVertexAttrib4f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+193)
#define FUNID_glViewport ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+194)
#define FUNID_glReadBuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+195)
#define FUNID_glCopyTexSubImage3D ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+196)
#define FUNID_glBeginQuery ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+197)
#define FUNID_glEndQuery ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+198)
#define FUNID_glBlitFramebuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+199)
#define FUNID_glRenderbufferStorageMultisample ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+200)
#define FUNID_glFramebufferTextureLayer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+201)
#define FUNID_glBindVertexArray_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+202)
#define FUNID_glBeginTransformFeedback ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+203)
#define FUNID_glEndTransformFeedback ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+204)
#define FUNID_glBindBufferRange ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+205)
#define FUNID_glBindBufferBase ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+206)
#define FUNID_glVertexAttribI4i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+207)
#define FUNID_glVertexAttribI4ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+208)
#define FUNID_glUniform1ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+209)
#define FUNID_glUniform2ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+210)
#define FUNID_glUniform3ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+211)
#define FUNID_glUniform4ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+212)
#define FUNID_glClearBufferfi ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+213)
#define FUNID_glCopyBufferSubData ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+214)
#define FUNID_glUniformBlockBinding ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+215)
#define FUNID_glDrawArraysInstanced_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+216)
#define FUNID_glBindSampler ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+217)
#define FUNID_glSamplerParameteri ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+218)
#define FUNID_glSamplerParameterf ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+219)
#define FUNID_glVertexAttribDivisor_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+220)
#define FUNID_glBindTransformFeedback ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+221)
#define FUNID_glPauseTransformFeedback ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+222)
#define FUNID_glResumeTransformFeedback ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+223)
#define FUNID_glProgramParameteri ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+224)
#define FUNID_glTexStorage2D ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+225)
#define FUNID_glTexStorage3D ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+226)
#define FUNID_glAlphaFuncxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+227)
#define FUNID_glClearColorxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+228)
#define FUNID_glClearDepthxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+229)
#define FUNID_glColor4xOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+230)
#define FUNID_glDepthRangexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+231)
#define FUNID_glFogxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+232)
#define FUNID_glFrustumxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+233)
#define FUNID_glLightModelxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+234)
#define FUNID_glLightxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+235)
#define FUNID_glLineWidthxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+236)
#define FUNID_glMaterialxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+237)
#define FUNID_glMultiTexCoord4xOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+238)
#define FUNID_glNormal3xOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+239)
#define FUNID_glOrthoxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+240)
#define FUNID_glPointSizexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+241)
#define FUNID_glPolygonOffsetxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+242)
#define FUNID_glRotatexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+243)
#define FUNID_glScalexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+244)
#define FUNID_glTexEnvxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+245)
#define FUNID_glTranslatexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+246)
#define FUNID_glPointParameterxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+247)
#define FUNID_glSampleCoveragexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+248)
#define FUNID_glTexGenxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+249)
#define FUNID_glClearDepthfOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+250)
#define FUNID_glDepthRangefOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+251)
#define FUNID_glFrustumfOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+252)
#define FUNID_glOrthofOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+253)
#define FUNID_glRenderbufferStorageMultisampleEXT ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+254)
#define FUNID_glUseProgramStages ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+255)
#define FUNID_glActiveShaderProgram ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+256)
#define FUNID_glProgramUniform1i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+257)
#define FUNID_glProgramUniform2i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+258)
#define FUNID_glProgramUniform3i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+259)
#define FUNID_glProgramUniform4i ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+260)
#define FUNID_glProgramUniform1ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+261)
#define FUNID_glProgramUniform2ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+262)
#define FUNID_glProgramUniform3ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+263)
#define FUNID_glProgramUniform4ui ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+264)
#define FUNID_glProgramUniform1f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+265)
#define FUNID_glProgramUniform2f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+266)
#define FUNID_glProgramUniform3f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+267)
#define FUNID_glProgramUniform4f ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+268)
#define FUNID_glDeleteBuffers_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+269)
#define FUNID_glDeleteFramebuffers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+270)
#define FUNID_glDeleteRenderbuffers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+271)
#define FUNID_glDeleteTextures ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+272)
#define FUNID_glDrawElements_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+273)
#define FUNID_glShaderBinary ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+274)
#define FUNID_glCompressedTexSubImage2D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+275)
#define FUNID_glTexImage2D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+276)
#define FUNID_glTexParameterfv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+277)
#define FUNID_glTexParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+278)
#define FUNID_glTexSubImage2D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+279)
#define FUNID_glUniform1fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+280)
#define FUNID_glUniform1iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+281)
#define FUNID_glUniform2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+282)
#define FUNID_glUniform2iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+283)
#define FUNID_glUniform3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+284)
#define FUNID_glUniform3iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+285)
#define FUNID_glUniform4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+286)
#define FUNID_glUniform4iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+287)
#define FUNID_glVertexAttrib1fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+288)
#define FUNID_glVertexAttrib2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+289)
#define FUNID_glVertexAttrib3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+290)
#define FUNID_glVertexAttrib4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+291)
#define FUNID_glVertexAttribPointer_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+292)
#define FUNID_glVertexAttribPointer_offset ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+293)
#define FUNID_glDrawRangeElements_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+294)
#define FUNID_glTexImage3D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+295)
#define FUNID_glTexSubImage3D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+296)
#define FUNID_glCompressedTexImage3D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+297)
#define FUNID_glCompressedTexSubImage3D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+298)
#define FUNID_glCompressedTexImage2D_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+299)
#define FUNID_glDeleteQueries ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+300)
#define FUNID_glDrawBuffers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+301)
#define FUNID_glUniformMatrix2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+302)
#define FUNID_glUniformMatrix3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+303)
#define FUNID_glUniformMatrix4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+304)
#define FUNID_glUniformMatrix2x3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+305)
#define FUNID_glUniformMatrix3x2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+306)
#define FUNID_glUniformMatrix2x4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+307)
#define FUNID_glUniformMatrix4x2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+308)
#define FUNID_glUniformMatrix3x4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+309)
#define FUNID_glUniformMatrix4x3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+310)
#define FUNID_glDeleteVertexArrays_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+311)
#define FUNID_glVertexAttribIPointer_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+312)
#define FUNID_glVertexAttribIPointer_offset ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+313)
#define FUNID_glVertexAttribI4iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+314)
#define FUNID_glVertexAttribI4uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+315)
#define FUNID_glUniform1uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+316)
#define FUNID_glUniform2uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+317)
#define FUNID_glUniform3uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+318)
#define FUNID_glUniform4uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+319)
#define FUNID_glClearBufferiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+320)
#define FUNID_glClearBufferuiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+321)
#define FUNID_glClearBufferfv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+322)
#define FUNID_glDrawElementsInstanced_with_bound ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+323)
#define FUNID_glDeleteSamplers ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+324)
#define FUNID_glSamplerParameteriv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+325)
#define FUNID_glSamplerParameterfv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+326)
#define FUNID_glDeleteTransformFeedbacks ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+327)
#define FUNID_glProgramBinary ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+328)
#define FUNID_glInvalidateFramebuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+329)
#define FUNID_glInvalidateSubFramebuffer ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+330)
#define FUNID_glClipPlanexOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+331)
#define FUNID_glFogxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+332)
#define FUNID_glLightModelxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+333)
#define FUNID_glLightxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+334)
#define FUNID_glLoadMatrixxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+335)
#define FUNID_glMaterialxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+336)
#define FUNID_glMultMatrixxOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+337)
#define FUNID_glPointParameterxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+338)
#define FUNID_glTexEnvxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+339)
#define FUNID_glClipPlanefOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+340)
#define FUNID_glTexGenxvOES ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+341)
#define FUNID_glDeleteProgramPipelines ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+342)
#define FUNID_glProgramUniform1iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+343)
#define FUNID_glProgramUniform2iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+344)
#define FUNID_glProgramUniform3iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+345)
#define FUNID_glProgramUniform4iv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+346)
#define FUNID_glProgramUniform1uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+347)
#define FUNID_glProgramUniform2uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+348)
#define FUNID_glProgramUniform3uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+349)
#define FUNID_glProgramUniform4uiv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+350)
#define FUNID_glProgramUniform1fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+351)
#define FUNID_glProgramUniform2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+352)
#define FUNID_glProgramUniform3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+353)
#define FUNID_glProgramUniform4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+354)
#define FUNID_glProgramUniformMatrix2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+355)
#define FUNID_glProgramUniformMatrix3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+356)
#define FUNID_glProgramUniformMatrix4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+357)
#define FUNID_glProgramUniformMatrix2x3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+358)
#define FUNID_glProgramUniformMatrix3x2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+359)
#define FUNID_glProgramUniformMatrix2x4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+360)
#define FUNID_glProgramUniformMatrix4x2fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+361)
#define FUNID_glProgramUniformMatrix3x4fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+362)
#define FUNID_glProgramUniformMatrix4x3fv ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+363)
#define FUNID_glFlushMappedBufferRange_origin ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+364)
#define FUNID_glDeleteSync ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+365)
#define FUNID_glWaitSync ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+366)
#define FUNID_glTestIntAsyn ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+367)
#define FUNID_glPrintfAsyn ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x2+0x1)<<24u)+368)
#define FUNID_glVertexAttribPointer_data ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x1)<<24u)+369)
#define FUNID_glVertexAttribIPointer_data ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x1)<<24u)+370)
#define FUNID_glMapBufferRange_write ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x1)<<24u)+371)
#define FUNID_glSaveLongTime ((EXPRESS_GPU_FUN_ID<<32u)+(((unsigned long long)0+0x1)<<24u)+372)






#define PARA_NUM_MIN_glMapBufferRange_read (2)
#define PARA_NUM_MIN_glCheckFramebufferStatus (1)
#define PARA_NUM_MIN_glCreateProgram (0)
#define PARA_NUM_MIN_glCreateShader (1)
#define PARA_NUM_MIN_glGetError (0)
#define PARA_NUM_MIN_glIsBuffer (1)
#define PARA_NUM_MIN_glIsEnabled (1)
#define PARA_NUM_MIN_glIsFramebuffer (1)
#define PARA_NUM_MIN_glIsProgram (1)
#define PARA_NUM_MIN_glIsRenderbuffer (1)
#define PARA_NUM_MIN_glIsShader (1)
#define PARA_NUM_MIN_glIsTexture (1)
#define PARA_NUM_MIN_glIsQuery (1)
#define PARA_NUM_MIN_glIsVertexArray (1)
#define PARA_NUM_MIN_glIsSampler (1)
#define PARA_NUM_MIN_glIsTransformFeedback (1)
#define PARA_NUM_MIN_glGetAttribLocation (2)
#define PARA_NUM_MIN_glGetUniformLocation (2)
#define PARA_NUM_MIN_glGetFragDataLocation (2)
#define PARA_NUM_MIN_glGetUniformBlockIndex (2)
#define PARA_NUM_MIN_glGetProgramResourceIndex (2)
#define PARA_NUM_MIN_glGetProgramResourceLocation (2)
#define PARA_NUM_MIN_glCreateShaderProgramv (2)
#define PARA_NUM_MIN_glQueryMatrixxOES (2)
#define PARA_NUM_MIN_glGenBuffers (2)
#define PARA_NUM_MIN_glGenFramebuffers (2)
#define PARA_NUM_MIN_glGenRenderbuffers (2)
#define PARA_NUM_MIN_glGenTextures (2)
#define PARA_NUM_MIN_glGetActiveAttrib (5)
#define PARA_NUM_MIN_glGetActiveUniform (5)
#define PARA_NUM_MIN_glGetAttachedShaders (3)
#define PARA_NUM_MIN_glGetBooleanv (2)
#define PARA_NUM_MIN_glGetBufferParameteriv (2)
#define PARA_NUM_MIN_glGetFloatv (2)
#define PARA_NUM_MIN_glGetFramebufferAttachmentParameteriv (2)
#define PARA_NUM_MIN_glGetIntegerv (2)
#define PARA_NUM_MIN_glGetProgramiv (2)
#define PARA_NUM_MIN_glGetProgramInfoLog (3)
#define PARA_NUM_MIN_glGetRenderbufferParameteriv (2)
#define PARA_NUM_MIN_glGetShaderiv (2)
#define PARA_NUM_MIN_glGetShaderInfoLog (3)
#define PARA_NUM_MIN_glGetShaderPrecisionFormat (3)
#define PARA_NUM_MIN_glGetShaderSource (3)
#define PARA_NUM_MIN_glGetTexParameterfv (2)
#define PARA_NUM_MIN_glGetTexParameteriv (2)
#define PARA_NUM_MIN_glGetUniformfv (2)
#define PARA_NUM_MIN_glGetUniformiv (2)
#define PARA_NUM_MIN_glGetUniformuiv (2)
#define PARA_NUM_MIN_glGetUniformIndices (3)
#define PARA_NUM_MIN_glGetVertexAttribfv_origin (2)
#define PARA_NUM_MIN_glGetVertexAttribiv_origin (2)
#define PARA_NUM_MIN_glReadPixels_without_bound (2)
#define PARA_NUM_MIN_glReadPixels_with_bound (1)
#define PARA_NUM_MIN_glGenQueries (2)
#define PARA_NUM_MIN_glGetQueryiv (2)
#define PARA_NUM_MIN_glGetQueryObjectuiv (2)
#define PARA_NUM_MIN_glGenVertexArrays_origin (2)
#define PARA_NUM_MIN_glGetIntegeri_v (2)
#define PARA_NUM_MIN_glGetTransformFeedbackVarying (5)
#define PARA_NUM_MIN_glGetVertexAttribIiv_origin (2)
#define PARA_NUM_MIN_glGetVertexAttribIuiv_origin (2)
#define PARA_NUM_MIN_glGetActiveUniformsiv (3)
#define PARA_NUM_MIN_glGetActiveUniformBlockiv (2)
#define PARA_NUM_MIN_glGetActiveUniformBlockName (3)
#define PARA_NUM_MIN_glGetInteger64v (2)
#define PARA_NUM_MIN_glGetInteger64i_v (2)
#define PARA_NUM_MIN_glGetBufferParameteri64v (2)
#define PARA_NUM_MIN_glGenSamplers (2)
#define PARA_NUM_MIN_glGetSamplerParameteriv (2)
#define PARA_NUM_MIN_glGetSamplerParameterfv (2)
#define PARA_NUM_MIN_glGenTransformFeedbacks (2)
#define PARA_NUM_MIN_glGetProgramBinary (4)
#define PARA_NUM_MIN_glGetInternalformativ (2)
#define PARA_NUM_MIN_glGetClipPlanexOES (2)
#define PARA_NUM_MIN_glGetFixedvOES (2)
#define PARA_NUM_MIN_glGetTexEnvxvOES (2)
#define PARA_NUM_MIN_glGetTexParameterxvOES (2)
#define PARA_NUM_MIN_glGetLightxvOES (2)
#define PARA_NUM_MIN_glGetMaterialxvOES (2)
#define PARA_NUM_MIN_glGetTexGenxvOES (2)
#define PARA_NUM_MIN_glShaderSource (3)
#define PARA_NUM_MIN_glTransformFeedbackVaryings (2)
#define PARA_NUM_MIN_glGetFramebufferParameteriv (2)
#define PARA_NUM_MIN_glGetProgramInterfaceiv (2)
#define PARA_NUM_MIN_glGetProgramResourceName (3)
#define PARA_NUM_MIN_glGetProgramResourceiv (4)
#define PARA_NUM_MIN_glGenProgramPipelines (2)
#define PARA_NUM_MIN_glGetProgramPipelineiv (2)
#define PARA_NUM_MIN_glGetProgramPipelineInfoLog (3)
#define PARA_NUM_MIN_glGetBooleani_v (2)
#define PARA_NUM_MIN_glGetMultisamplefv (2)
#define PARA_NUM_MIN_glGetTexLevelParameteriv (2)
#define PARA_NUM_MIN_glGetTexLevelParameterfv (2)
#define PARA_NUM_MIN_glFenceSync (1)
#define PARA_NUM_MIN_glIsSync (1)
#define PARA_NUM_MIN_glGetSynciv (3)
#define PARA_NUM_MIN_glClientWaitSync (1)
#define PARA_NUM_MIN_glFinish (0)
#define PARA_NUM_MIN_glUnmapBuffer_special (1)
#define PARA_NUM_MIN_glBindAttribLocation (2)
#define PARA_NUM_MIN_glBufferData_custom (2)
#define PARA_NUM_MIN_glBufferSubData_custom (2)
#define PARA_NUM_MIN_glCompressedTexImage2D_without_bound (2)
#define PARA_NUM_MIN_glCompressedTexSubImage2D_without_bound (2)
#define PARA_NUM_MIN_glDrawElements_without_bound (2)
#define PARA_NUM_MIN_glTexImage2D_without_bound (2)
#define PARA_NUM_MIN_glDrawRangeElements_without_bound (2)
#define PARA_NUM_MIN_glCompressedTexImage3D_without_bound (2)
#define PARA_NUM_MIN_glCompressedTexSubImage3D_without_bound (2)
#define PARA_NUM_MIN_glTexSubImage2D_without_bound (2)
#define PARA_NUM_MIN_glTexImage3D_without_bound (2)
#define PARA_NUM_MIN_glTexSubImage3D_without_bound (2)
#define PARA_NUM_MIN_glDrawElementsInstanced_without_bound (2)
#define PARA_NUM_MIN_glTestInt1 (1)
#define PARA_NUM_MIN_glTestInt2 (1)
#define PARA_NUM_MIN_glTestInt3 (1)
#define PARA_NUM_MIN_glTestInt4 (1)
#define PARA_NUM_MIN_glTestInt5 (1)
#define PARA_NUM_MIN_glTestInt6 (1)
#define PARA_NUM_MIN_glTestPointer1 (2)
#define PARA_NUM_MIN_glTestPointer2 (3)
#define PARA_NUM_MIN_glTestPointer3 (3)
#define PARA_NUM_MIN_glTestPointer4 (3)
#define PARA_NUM_MIN_glTestString (3)
#define PARA_NUM_MIN_glPrintf (2)
#define PARA_NUM_MIN_glInOutTest (5)
#define PARA_NUM_MIN_glActiveTexture (1)
#define PARA_NUM_MIN_glAttachShader (1)
#define PARA_NUM_MIN_glBindBuffer_origin (1)
#define PARA_NUM_MIN_glBindFramebuffer (1)
#define PARA_NUM_MIN_glBindRenderbuffer (1)
#define PARA_NUM_MIN_glBindTexture (1)
#define PARA_NUM_MIN_glBlendColor (1)
#define PARA_NUM_MIN_glBlendEquation (1)
#define PARA_NUM_MIN_glBlendEquationSeparate (1)
#define PARA_NUM_MIN_glBlendFunc (1)
#define PARA_NUM_MIN_glBlendFuncSeparate (1)
#define PARA_NUM_MIN_glClear (1)
#define PARA_NUM_MIN_glClearColor (1)
#define PARA_NUM_MIN_glClearDepthf (1)
#define PARA_NUM_MIN_glClearStencil (1)
#define PARA_NUM_MIN_glColorMask (1)
#define PARA_NUM_MIN_glCompileShader (1)
#define PARA_NUM_MIN_glCopyTexImage2D (1)
#define PARA_NUM_MIN_glCopyTexSubImage2D (1)
#define PARA_NUM_MIN_glCullFace (1)
#define PARA_NUM_MIN_glDeleteProgram_origin (1)
#define PARA_NUM_MIN_glDeleteShader (1)
#define PARA_NUM_MIN_glDepthFunc (1)
#define PARA_NUM_MIN_glDepthMask (1)
#define PARA_NUM_MIN_glDepthRangef (1)
#define PARA_NUM_MIN_glDetachShader (1)
#define PARA_NUM_MIN_glDisable (1)
#define PARA_NUM_MIN_glDisableVertexAttribArray_origin (1)
#define PARA_NUM_MIN_glDrawArrays_origin (1)
#define PARA_NUM_MIN_glEnable (1)
#define PARA_NUM_MIN_glEnableVertexAttribArray_origin (1)
#define PARA_NUM_MIN_glFlush (0)
#define PARA_NUM_MIN_glFramebufferRenderbuffer (1)
#define PARA_NUM_MIN_glFramebufferTexture2D (1)
#define PARA_NUM_MIN_glFrontFace (1)
#define PARA_NUM_MIN_glGenerateMipmap (1)
#define PARA_NUM_MIN_glHint (1)
#define PARA_NUM_MIN_glLineWidth (1)
#define PARA_NUM_MIN_glLinkProgram_origin (1)
#define PARA_NUM_MIN_glPixelStorei_origin (1)
#define PARA_NUM_MIN_glPolygonOffset (1)
#define PARA_NUM_MIN_glReleaseShaderCompiler (0)
#define PARA_NUM_MIN_glRenderbufferStorage (1)
#define PARA_NUM_MIN_glSampleCoverage (1)
#define PARA_NUM_MIN_glScissor (1)
#define PARA_NUM_MIN_glStencilFunc (1)
#define PARA_NUM_MIN_glStencilFuncSeparate (1)
#define PARA_NUM_MIN_glStencilMask (1)
#define PARA_NUM_MIN_glStencilMaskSeparate (1)
#define PARA_NUM_MIN_glStencilOp (1)
#define PARA_NUM_MIN_glStencilOpSeparate (1)
#define PARA_NUM_MIN_glTexParameterf (1)
#define PARA_NUM_MIN_glTexParameteri (1)
#define PARA_NUM_MIN_glUniform1f (1)
#define PARA_NUM_MIN_glUniform1i (1)
#define PARA_NUM_MIN_glUniform2f (1)
#define PARA_NUM_MIN_glUniform2i (1)
#define PARA_NUM_MIN_glUniform3f (1)
#define PARA_NUM_MIN_glUniform3i (1)
#define PARA_NUM_MIN_glUniform4f (1)
#define PARA_NUM_MIN_glUniform4i (1)
#define PARA_NUM_MIN_glUseProgram (1)
#define PARA_NUM_MIN_glValidateProgram (1)
#define PARA_NUM_MIN_glVertexAttrib1f (1)
#define PARA_NUM_MIN_glVertexAttrib2f (1)
#define PARA_NUM_MIN_glVertexAttrib3f (1)
#define PARA_NUM_MIN_glVertexAttrib4f (1)
#define PARA_NUM_MIN_glViewport (1)
#define PARA_NUM_MIN_glReadBuffer (1)
#define PARA_NUM_MIN_glCopyTexSubImage3D (1)
#define PARA_NUM_MIN_glBeginQuery (1)
#define PARA_NUM_MIN_glEndQuery (1)
#define PARA_NUM_MIN_glBlitFramebuffer (1)
#define PARA_NUM_MIN_glRenderbufferStorageMultisample (1)
#define PARA_NUM_MIN_glFramebufferTextureLayer (1)
#define PARA_NUM_MIN_glBindVertexArray_origin (1)
#define PARA_NUM_MIN_glBeginTransformFeedback (1)
#define PARA_NUM_MIN_glEndTransformFeedback (0)
#define PARA_NUM_MIN_glBindBufferRange (1)
#define PARA_NUM_MIN_glBindBufferBase (1)
#define PARA_NUM_MIN_glVertexAttribI4i (1)
#define PARA_NUM_MIN_glVertexAttribI4ui (1)
#define PARA_NUM_MIN_glUniform1ui (1)
#define PARA_NUM_MIN_glUniform2ui (1)
#define PARA_NUM_MIN_glUniform3ui (1)
#define PARA_NUM_MIN_glUniform4ui (1)
#define PARA_NUM_MIN_glClearBufferfi (1)
#define PARA_NUM_MIN_glCopyBufferSubData (1)
#define PARA_NUM_MIN_glUniformBlockBinding (1)
#define PARA_NUM_MIN_glDrawArraysInstanced_origin (1)
#define PARA_NUM_MIN_glBindSampler (1)
#define PARA_NUM_MIN_glSamplerParameteri (1)
#define PARA_NUM_MIN_glSamplerParameterf (1)
#define PARA_NUM_MIN_glVertexAttribDivisor_origin (1)
#define PARA_NUM_MIN_glBindTransformFeedback (1)
#define PARA_NUM_MIN_glPauseTransformFeedback (0)
#define PARA_NUM_MIN_glResumeTransformFeedback (0)
#define PARA_NUM_MIN_glProgramParameteri (1)
#define PARA_NUM_MIN_glTexStorage2D (1)
#define PARA_NUM_MIN_glTexStorage3D (1)
#define PARA_NUM_MIN_glAlphaFuncxOES (1)
#define PARA_NUM_MIN_glClearColorxOES (1)
#define PARA_NUM_MIN_glClearDepthxOES (1)
#define PARA_NUM_MIN_glColor4xOES (1)
#define PARA_NUM_MIN_glDepthRangexOES (1)
#define PARA_NUM_MIN_glFogxOES (1)
#define PARA_NUM_MIN_glFrustumxOES (1)
#define PARA_NUM_MIN_glLightModelxOES (1)
#define PARA_NUM_MIN_glLightxOES (1)
#define PARA_NUM_MIN_glLineWidthxOES (1)
#define PARA_NUM_MIN_glMaterialxOES (1)
#define PARA_NUM_MIN_glMultiTexCoord4xOES (1)
#define PARA_NUM_MIN_glNormal3xOES (1)
#define PARA_NUM_MIN_glOrthoxOES (1)
#define PARA_NUM_MIN_glPointSizexOES (1)
#define PARA_NUM_MIN_glPolygonOffsetxOES (1)
#define PARA_NUM_MIN_glRotatexOES (1)
#define PARA_NUM_MIN_glScalexOES (1)
#define PARA_NUM_MIN_glTexEnvxOES (1)
#define PARA_NUM_MIN_glTranslatexOES (1)
#define PARA_NUM_MIN_glPointParameterxOES (1)
#define PARA_NUM_MIN_glSampleCoveragexOES (1)
#define PARA_NUM_MIN_glTexGenxOES (1)
#define PARA_NUM_MIN_glClearDepthfOES (1)
#define PARA_NUM_MIN_glDepthRangefOES (1)
#define PARA_NUM_MIN_glFrustumfOES (1)
#define PARA_NUM_MIN_glOrthofOES (1)
#define PARA_NUM_MIN_glRenderbufferStorageMultisampleEXT (1)
#define PARA_NUM_MIN_glUseProgramStages (1)
#define PARA_NUM_MIN_glActiveShaderProgram (1)
#define PARA_NUM_MIN_glProgramUniform1i (1)
#define PARA_NUM_MIN_glProgramUniform2i (1)
#define PARA_NUM_MIN_glProgramUniform3i (1)
#define PARA_NUM_MIN_glProgramUniform4i (1)
#define PARA_NUM_MIN_glProgramUniform1ui (1)
#define PARA_NUM_MIN_glProgramUniform2ui (1)
#define PARA_NUM_MIN_glProgramUniform3ui (1)
#define PARA_NUM_MIN_glProgramUniform4ui (1)
#define PARA_NUM_MIN_glProgramUniform1f (1)
#define PARA_NUM_MIN_glProgramUniform2f (1)
#define PARA_NUM_MIN_glProgramUniform3f (1)
#define PARA_NUM_MIN_glProgramUniform4f (1)
#define PARA_NUM_MIN_glDeleteBuffers_origin (1)
#define PARA_NUM_MIN_glDeleteFramebuffers (1)
#define PARA_NUM_MIN_glDeleteRenderbuffers (1)
#define PARA_NUM_MIN_glDeleteTextures (1)
#define PARA_NUM_MIN_glDrawElements_with_bound (1)
#define PARA_NUM_MIN_glShaderBinary (1)
#define PARA_NUM_MIN_glCompressedTexSubImage2D_with_bound (1)
#define PARA_NUM_MIN_glTexImage2D_with_bound (1)
#define PARA_NUM_MIN_glTexParameterfv (1)
#define PARA_NUM_MIN_glTexParameteriv (1)
#define PARA_NUM_MIN_glTexSubImage2D_with_bound (1)
#define PARA_NUM_MIN_glUniform1fv (1)
#define PARA_NUM_MIN_glUniform1iv (1)
#define PARA_NUM_MIN_glUniform2fv (1)
#define PARA_NUM_MIN_glUniform2iv (1)
#define PARA_NUM_MIN_glUniform3fv (1)
#define PARA_NUM_MIN_glUniform3iv (1)
#define PARA_NUM_MIN_glUniform4fv (1)
#define PARA_NUM_MIN_glUniform4iv (1)
#define PARA_NUM_MIN_glVertexAttrib1fv (1)
#define PARA_NUM_MIN_glVertexAttrib2fv (1)
#define PARA_NUM_MIN_glVertexAttrib3fv (1)
#define PARA_NUM_MIN_glVertexAttrib4fv (1)
#define PARA_NUM_MIN_glVertexAttribPointer_with_bound (1)
#define PARA_NUM_MIN_glVertexAttribPointer_offset (1)
#define PARA_NUM_MIN_glDrawRangeElements_with_bound (1)
#define PARA_NUM_MIN_glTexImage3D_with_bound (1)
#define PARA_NUM_MIN_glTexSubImage3D_with_bound (1)
#define PARA_NUM_MIN_glCompressedTexImage3D_with_bound (1)
#define PARA_NUM_MIN_glCompressedTexSubImage3D_with_bound (1)
#define PARA_NUM_MIN_glCompressedTexImage2D_with_bound (1)
#define PARA_NUM_MIN_glDeleteQueries (1)
#define PARA_NUM_MIN_glDrawBuffers (1)
#define PARA_NUM_MIN_glUniformMatrix2fv (1)
#define PARA_NUM_MIN_glUniformMatrix3fv (1)
#define PARA_NUM_MIN_glUniformMatrix4fv (1)
#define PARA_NUM_MIN_glUniformMatrix2x3fv (1)
#define PARA_NUM_MIN_glUniformMatrix3x2fv (1)
#define PARA_NUM_MIN_glUniformMatrix2x4fv (1)
#define PARA_NUM_MIN_glUniformMatrix4x2fv (1)
#define PARA_NUM_MIN_glUniformMatrix3x4fv (1)
#define PARA_NUM_MIN_glUniformMatrix4x3fv (1)
#define PARA_NUM_MIN_glDeleteVertexArrays_origin (1)
#define PARA_NUM_MIN_glVertexAttribIPointer_with_bound (1)
#define PARA_NUM_MIN_glVertexAttribIPointer_offset (1)
#define PARA_NUM_MIN_glVertexAttribI4iv (1)
#define PARA_NUM_MIN_glVertexAttribI4uiv (1)
#define PARA_NUM_MIN_glUniform1uiv (1)
#define PARA_NUM_MIN_glUniform2uiv (1)
#define PARA_NUM_MIN_glUniform3uiv (1)
#define PARA_NUM_MIN_glUniform4uiv (1)
#define PARA_NUM_MIN_glClearBufferiv (1)
#define PARA_NUM_MIN_glClearBufferuiv (1)
#define PARA_NUM_MIN_glClearBufferfv (1)
#define PARA_NUM_MIN_glDrawElementsInstanced_with_bound (1)
#define PARA_NUM_MIN_glDeleteSamplers (1)
#define PARA_NUM_MIN_glSamplerParameteriv (1)
#define PARA_NUM_MIN_glSamplerParameterfv (1)
#define PARA_NUM_MIN_glDeleteTransformFeedbacks (1)
#define PARA_NUM_MIN_glProgramBinary (1)
#define PARA_NUM_MIN_glInvalidateFramebuffer (1)
#define PARA_NUM_MIN_glInvalidateSubFramebuffer (1)
#define PARA_NUM_MIN_glClipPlanexOES (1)
#define PARA_NUM_MIN_glFogxvOES (1)
#define PARA_NUM_MIN_glLightModelxvOES (1)
#define PARA_NUM_MIN_glLightxvOES (1)
#define PARA_NUM_MIN_glLoadMatrixxOES (1)
#define PARA_NUM_MIN_glMaterialxvOES (1)
#define PARA_NUM_MIN_glMultMatrixxOES (1)
#define PARA_NUM_MIN_glPointParameterxvOES (1)
#define PARA_NUM_MIN_glTexEnvxvOES (1)
#define PARA_NUM_MIN_glClipPlanefOES (1)
#define PARA_NUM_MIN_glTexGenxvOES (1)
#define PARA_NUM_MIN_glDeleteProgramPipelines (1)
#define PARA_NUM_MIN_glProgramUniform1iv (1)
#define PARA_NUM_MIN_glProgramUniform2iv (1)
#define PARA_NUM_MIN_glProgramUniform3iv (1)
#define PARA_NUM_MIN_glProgramUniform4iv (1)
#define PARA_NUM_MIN_glProgramUniform1uiv (1)
#define PARA_NUM_MIN_glProgramUniform2uiv (1)
#define PARA_NUM_MIN_glProgramUniform3uiv (1)
#define PARA_NUM_MIN_glProgramUniform4uiv (1)
#define PARA_NUM_MIN_glProgramUniform1fv (1)
#define PARA_NUM_MIN_glProgramUniform2fv (1)
#define PARA_NUM_MIN_glProgramUniform3fv (1)
#define PARA_NUM_MIN_glProgramUniform4fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix2fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix3fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix4fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix2x3fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix3x2fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix2x4fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix4x2fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix3x4fv (1)
#define PARA_NUM_MIN_glProgramUniformMatrix4x3fv (1)
#define PARA_NUM_MIN_glFlushMappedBufferRange_origin (1)
#define PARA_NUM_MIN_glDeleteSync (1)
#define PARA_NUM_MIN_glWaitSync (1)
#define PARA_NUM_MIN_glTestIntAsyn (1)
#define PARA_NUM_MIN_glPrintfAsyn (1)
#define PARA_NUM_MIN_glVertexAttribPointer_data (2)
#define PARA_NUM_MIN_glVertexAttribIPointer_data (2)
#define PARA_NUM_MIN_glMapBufferRange_write (2)
#define PARA_NUM_MIN_glSaveLongTime (2)



void gl3_decode_invoke(Render_Thread_Context *context,Direct_Express_Call *call);

#endif
